-- Emp_GetAll
IF OBJECT_ID(N'[dbo].[Emp_GetAll]', N'P') IS NOT NULL
    DROP PROCEDURE [dbo].[Emp_GetAll];
GO
CREATE PROCEDURE [dbo].[Emp_GetAll]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        Id,
        FirstName,
        LastName,
        DOB,
        DOJ,
        ProbationStartDate,
        ProbationPeriod,
        ConfirmationDate,
        PANNumber,
        ESICNumber,
        PFNumeber,
        CurrentAddress1,
        CurrentAddress2,
        CurrentCityId,
        CurrentStateId,
        CurrentCountryId,
        CurrentZipCode,
        PermanentAddress1,
        PermanentAddress2,
        PermanentCityId,
        PermanentStateId,
        PermanentCountryId,
        PermanentZipCode,
        PhoneNumber,
        MobileNumber,
        EmailId,
        DepartmentId,
        DesignationId,
        PaymentModeId,
        EmployeeTypeId,
        CategoryId,
        BankAccountNumber,
        BankName,
        GenderId,
        BloodGroupId,
        GradeId,
        Image,
        EmployeeOldId,
        FathersName,
        MothersName,
        Description,
        LicenceNumber,
        LicenceIssueDate,
        LicenceValidUpto,
        LicenceDescription,
        LicenceImage,
        LicenceType,
        Salutation,
        DateOfLeaving,
        MaritalStatus,
        YearsOfExperience,
        PrevioudSchoolCompany,
        AadhaarNumber,
        MathUpToClass,
        EnglishUptoClass,
        SSTUptoClass,
        CompanyId,
        SchoolId,
        IsActive,
        IsDeleted,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        ModifiedDate,
        [Status],
        StatusMessage
    FROM [dbo].[EmpMaster]
    WHERE IsDeleted = 0;
END
GO

-- Emp_GetById
IF OBJECT_ID(N'[dbo].[Emp_GetById]', N'P') IS NOT NULL
    DROP PROCEDURE [dbo].[Emp_GetById];
GO
CREATE PROCEDURE [dbo].[Emp_GetById]
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        Id,
        FirstName,
        LastName,
        DOB,
        DOJ,
        ProbationStartDate,
        ProbationPeriod,
        ConfirmationDate,
        PANNumber,
        ESICNumber,
        PFNumeber,
        CurrentAddress1,
        CurrentAddress2,
        CurrentCityId,
        CurrentStateId,
        CurrentCountryId,
        CurrentZipCode,
        PermanentAddress1,
        PermanentAddress2,
        PermanentCityId,
        PermanentStateId,
        PermanentCountryId,
        PermanentZipCode,
        PhoneNumber,
        MobileNumber,
        EmailId,
        DepartmentId,
        DesignationId,
        PaymentModeId,
        EmployeeTypeId,
        CategoryId,
        BankAccountNumber,
        BankName,
        GenderId,
        BloodGroupId,
        GradeId,
        Image,
        EmployeeOldId,
        FathersName,
        MothersName,
        Description,
        LicenceNumber,
        LicenceIssueDate,
        LicenceValidUpto,
        LicenceDescription,
        LicenceImage,
        LicenceType,
        Salutation,
        DateOfLeaving,
        MaritalStatus,
        YearsOfExperience,
        PrevioudSchoolCompany,
        AadhaarNumber,
        MathUpToClass,
        EnglishUptoClass,
        SSTUptoClass,
        CompanyId,
        SchoolId,
        IsActive,
        IsDeleted,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        ModifiedDate,
        [Status],
        StatusMessage
    FROM [dbo].[EmpMaster]
    WHERE Id = @Id;
END
GO

-- Emp_Create
IF OBJECT_ID(N'[dbo].[Emp_Create]', N'P') IS NOT NULL
    DROP PROCEDURE [dbo].[Emp_Create];
GO
CREATE PROCEDURE [dbo].[Emp_Create]
    @FirstName NVARCHAR(50),
    @LastName NVARCHAR(50),
    @DOB DATETIME,
    @DOJ DATETIME,
    @ProbationStartDate DATETIME = NULL,
    @ProbationPeriod INT = NULL,
    @ConfirmationDate DATETIME = NULL,
    @PANNumber NVARCHAR(50) = NULL,
    @ESICNumber NVARCHAR(50) = NULL,
    @PFNumeber NVARCHAR(50) = NULL,
    @CurrentAddress1 NVARCHAR(255) = NULL,
    @CurrentAddress2 NVARCHAR(255) = NULL,
    @CurrentCityId UNIQUEIDENTIFIER = NULL,
    @CurrentStateId UNIQUEIDENTIFIER = NULL,
    @CurrentCountryId UNIQUEIDENTIFIER = NULL,
    @CurrentZipCode NVARCHAR(50) = NULL,
    @PermanentAddress1 NVARCHAR(255) = NULL,
    @PermanentAddress2 NVARCHAR(255) = NULL,
    @PermanentCityId UNIQUEIDENTIFIER = NULL,
    @PermanentStateId UNIQUEIDENTIFIER = NULL,
    @PermanentCountryId UNIQUEIDENTIFIER = NULL,
    @PermanentZipCode NVARCHAR(50) = NULL,
    @PhoneNumber NVARCHAR(50) = NULL,
    @MobileNumber NVARCHAR(50) = NULL,
    @EmailId NVARCHAR(150) = NULL,
    @DepartmentId UNIQUEIDENTIFIER = NULL,
    @DesignationId UNIQUEIDENTIFIER = NULL,
    @PaymentModeId UNIQUEIDENTIFIER = NULL,
    @EmployeeTypeId UNIQUEIDENTIFIER = NULL,
    @CategoryId UNIQUEIDENTIFIER = NULL,
    @BankAccountNumber NVARCHAR(100) = NULL,
    @BankName NVARCHAR(100) = NULL,
    @GenderId UNIQUEIDENTIFIER = NULL,
    @BloodGroupId UNIQUEIDENTIFIER = NULL,
    @GradeId UNIQUEIDENTIFIER = NULL,
    @Image NVARCHAR(255) = NULL,
    @EmployeeOldId UNIQUEIDENTIFIER = NULL,
    @FathersName NVARCHAR(100) = NULL,
    @MothersName NVARCHAR(100) = NULL,
    @Description NVARCHAR(255) = NULL,
    @LicenceNumber NVARCHAR(50) = NULL,
    @LicenceIssueDate DATETIME = NULL,
    @LicenceValidUpto DATETIME = NULL,
    @LicenceDescription NVARCHAR(255) = NULL,
    @LicenceImage NVARCHAR(255) = NULL,
    @LicenceType NVARCHAR(50) = NULL,
    @Salutation NVARCHAR(20) = NULL,
    @DateOfLeaving DATETIME = NULL,
    @MaritalStatus NVARCHAR(50) = NULL,
    @YearsOfExperience NVARCHAR(50) = NULL,
    @PrevioudSchoolCompany NVARCHAR(150) = NULL,
    @AadhaarNumber NVARCHAR(20) = NULL,
    @MathUpToClass INT = NULL,
    @EnglishUptoClass INT = NULL,
    @SSTUptoClass INT = NULL,
    @CompanyId UNIQUEIDENTIFIER,
    @SchoolId UNIQUEIDENTIFIER,
    @IsActive BIT,
    @CreatedBy UNIQUEIDENTIFIER,
    @Status NVARCHAR(10) = NULL,
    @StatusMessage NVARCHAR(255) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @NewId UNIQUEIDENTIFIER = NEWID();

    INSERT INTO [dbo].[EmpMaster]
    (
        Id,
        FirstName,
        LastName,
        DOB,
        DOJ,
        ProbationStartDate,
        ProbationPeriod,
        ConfirmationDate,
        PANNumber,
        ESICNumber,
        PFNumeber,
        CurrentAddress1,
        CurrentAddress2,
        CurrentCityId,
        CurrentStateId,
        CurrentCountryId,
        CurrentZipCode,
        PermanentAddress1,
        PermanentAddress2,
        PermanentCityId,
        PermanentStateId,
        PermanentCountryId,
        PermanentZipCode,
        PhoneNumber,
        MobileNumber,
        EmailId,
        DepartmentId,
        DesignationId,
        PaymentModeId,
        EmployeeTypeId,
        CategoryId,
        BankAccountNumber,
        BankName,
        GenderId,
        BloodGroupId,
        GradeId,
        Image,
        EmployeeOldId,
        FathersName,
        MothersName,
        Description,
        LicenceNumber,
        LicenceIssueDate,
        LicenceValidUpto,
        LicenceDescription,
        LicenceImage,
        LicenceType,
        Salutation,
        DateOfLeaving,
        MaritalStatus,
        YearsOfExperience,
        PrevioudSchoolCompany,
        AadhaarNumber,
        MathUpToClass,
        EnglishUptoClass,
        SSTUptoClass,
        CompanyId,
        SchoolId,
        IsActive,
        IsDeleted,
        CreatedBy,
        CreatedDate,
        [Status],
        StatusMessage
    )
    VALUES
    (
        @NewId,
        @FirstName,
        @LastName,
        @DOB,
        @DOJ,
        @ProbationStartDate,
        @ProbationPeriod,
        @ConfirmationDate,
        @PANNumber,
        @ESICNumber,
        @PFNumeber,
        @CurrentAddress1,
        @CurrentAddress2,
        @CurrentCityId,
        @CurrentStateId,
        @CurrentCountryId,
        @CurrentZipCode,
        @PermanentAddress1,
        @PermanentAddress2,
        @PermanentCityId,
        @PermanentStateId,
        @PermanentCountryId,
        @PermanentZipCode,
        @PhoneNumber,
        @MobileNumber,
        @EmailId,
        @DepartmentId,
        @DesignationId,
        @PaymentModeId,
        @EmployeeTypeId,
        @CategoryId,
        @BankAccountNumber,
        @BankName,
        @GenderId,
        @BloodGroupId,
        @GradeId,
        @Image,
        @EmployeeOldId,
        @FathersName,
        @MothersName,
        @Description,
        @LicenceNumber,
        @LicenceIssueDate,
        @LicenceValidUpto,
        @LicenceDescription,
        @LicenceImage,
        @LicenceType,
        @Salutation,
        @DateOfLeaving,
        @MaritalStatus,
        @YearsOfExperience,
        @PrevioudSchoolCompany,
        @AadhaarNumber,
        @MathUpToClass,
        @EnglishUptoClass,
        @SSTUptoClass,
        @CompanyId,
        @SchoolId,
        @IsActive,
        0,
        @CreatedBy,
        SYSUTCDATETIME(),
        ISNULL(@Status, N''),
        ISNULL(@StatusMessage, N'')
    );

    SELECT Id = @NewId;
END
GO

-- Emp_Update
IF OBJECT_ID(N'[dbo].[Emp_Update]', N'P') IS NOT NULL
    DROP PROCEDURE [dbo].[Emp_Update];
GO
CREATE PROCEDURE [dbo].[Emp_Update]
    @Id UNIQUEIDENTIFIER,
    @FirstName NVARCHAR(50),
    @LastName NVARCHAR(50),
    @DOB DATETIME,
    @DOJ DATETIME,
    @ProbationStartDate DATETIME = NULL,
    @ProbationPeriod INT = NULL,
    @ConfirmationDate DATETIME = NULL,
    @PANNumber NVARCHAR(50) = NULL,
    @ESICNumber NVARCHAR(50) = NULL,
    @PFNumeber NVARCHAR(50) = NULL,
    @CurrentAddress1 NVARCHAR(255) = NULL,
    @CurrentAddress2 NVARCHAR(255) = NULL,
    @CurrentCityId UNIQUEIDENTIFIER = NULL,
    @CurrentStateId UNIQUEIDENTIFIER = NULL,
    @CurrentCountryId UNIQUEIDENTIFIER = NULL,
    @CurrentZipCode NVARCHAR(50) = NULL,
    @PermanentAddress1 NVARCHAR(255) = NULL,
    @PermanentAddress2 NVARCHAR(255) = NULL,
    @PermanentCityId UNIQUEIDENTIFIER = NULL,
    @PermanentStateId UNIQUEIDENTIFIER = NULL,
    @PermanentCountryId UNIQUEIDENTIFIER = NULL,
    @PermanentZipCode NVARCHAR(50) = NULL,
    @PhoneNumber NVARCHAR(50) = NULL,
    @MobileNumber NVARCHAR(50) = NULL,
    @EmailId NVARCHAR(150) = NULL,
    @DepartmentId UNIQUEIDENTIFIER = NULL,
    @DesignationId UNIQUEIDENTIFIER = NULL,
    @PaymentModeId UNIQUEIDENTIFIER = NULL,
    @EmployeeTypeId UNIQUEIDENTIFIER = NULL,
    @CategoryId UNIQUEIDENTIFIER = NULL,
    @BankAccountNumber NVARCHAR(100) = NULL,
    @BankName NVARCHAR(100) = NULL,
    @GenderId UNIQUEIDENTIFIER = NULL,
    @BloodGroupId UNIQUEIDENTIFIER = NULL,
    @GradeId UNIQUEIDENTIFIER = NULL,
    @Image NVARCHAR(255) = NULL,
    @EmployeeOldId UNIQUEIDENTIFIER = NULL,
    @FathersName NVARCHAR(100) = NULL,
    @MothersName NVARCHAR(100) = NULL,
    @Description NVARCHAR(255) = NULL,
    @LicenceNumber NVARCHAR(50) = NULL,
    @LicenceIssueDate DATETIME = NULL,
    @LicenceValidUpto DATETIME = NULL,
    @LicenceDescription NVARCHAR(255) = NULL,
    @LicenceImage NVARCHAR(255) = NULL,
    @LicenceType NVARCHAR(50) = NULL,
    @Salutation NVARCHAR(20) = NULL,
    @DateOfLeaving DATETIME = NULL,
    @MaritalStatus NVARCHAR(50) = NULL,
    @YearsOfExperience NVARCHAR(50) = NULL,
    @PrevioudSchoolCompany NVARCHAR(150) = NULL,
    @AadhaarNumber NVARCHAR(20) = NULL,
    @MathUpToClass INT = NULL,
    @EnglishUptoClass INT = NULL,
    @SSTUptoClass INT = NULL,
    @IsActive BIT,
    @ModifiedBy UNIQUEIDENTIFIER,
    @Status NVARCHAR(10) = NULL,
    @StatusMessage NVARCHAR(255) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[EmpMaster]
    SET 
        FirstName = @FirstName,
        LastName = @LastName,
        DOB = @DOB,
        DOJ = @DOJ,
        ProbationStartDate = @ProbationStartDate,
        ProbationPeriod = @ProbationPeriod,
        ConfirmationDate = @ConfirmationDate,
        PANNumber = @PANNumber,
        ESICNumber = @ESICNumber,
        PFNumeber = @PFNumeber,
        CurrentAddress1 = @CurrentAddress1,
        CurrentAddress2 = @CurrentAddress2,
        CurrentCityId = @CurrentCityId,
        CurrentStateId = @CurrentStateId,
        CurrentCountryId = @CurrentCountryId,
        CurrentZipCode = @CurrentZipCode,
        PermanentAddress1 = @PermanentAddress1,
        PermanentAddress2 = @PermanentAddress2,
        PermanentCityId = @PermanentCityId,
        PermanentStateId = @PermanentStateId,
        PermanentCountryId = @PermanentCountryId,
        PermanentZipCode = @PermanentZipCode,
        PhoneNumber = @PhoneNumber,
        MobileNumber = @MobileNumber,
        EmailId = @EmailId,
        DepartmentId = @DepartmentId,
        DesignationId = @DesignationId,
        PaymentModeId = @PaymentModeId,
        EmployeeTypeId = @EmployeeTypeId,
        CategoryId = @CategoryId,
        BankAccountNumber = @BankAccountNumber,
        BankName = @BankName,
        GenderId = @GenderId,
        BloodGroupId = @BloodGroupId,
        GradeId = @GradeId,
        Image = @Image,
        EmployeeOldId = @EmployeeOldId,
        FathersName = @FathersName,
        MothersName = @MothersName,
        Description = @Description,
        LicenceNumber = @LicenceNumber,
        LicenceIssueDate = @LicenceIssueDate,
        LicenceValidUpto = @LicenceValidUpto,
        LicenceDescription = @LicenceDescription,
        LicenceImage = @LicenceImage,
        LicenceType = @LicenceType,
        Salutation = @Salutation,
        DateOfLeaving = @DateOfLeaving,
        MaritalStatus = @MaritalStatus,
        YearsOfExperience = @YearsOfExperience,
        PrevioudSchoolCompany = @PrevioudSchoolCompany,
        AadhaarNumber = @AadhaarNumber,
        MathUpToClass = @MathUpToClass,
        EnglishUptoClass = @EnglishUptoClass,
        SSTUptoClass = @SSTUptoClass,
        IsActive = @IsActive,
        ModifiedBy = @ModifiedBy,
        ModifiedDate = SYSUTCDATETIME(),
        [Status] = ISNULL(@Status, [Status]),
        StatusMessage = ISNULL(@StatusMessage, StatusMessage)
    WHERE Id = @Id;

    RETURN 1;
END
GO

-- Emp_Delete (soft delete)
IF OBJECT_ID(N'[dbo].[Emp_Delete]', N'P') IS NOT NULL
    DROP PROCEDURE [dbo].[Emp_Delete];
GO
CREATE PROCEDURE [dbo].[Emp_Delete]
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[EmpMaster]
    SET IsDeleted = 1
    WHERE Id = @Id;

    RETURN 1;
END
GO
