<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DBAccess\DBAccess.csproj" />
    <ProjectReference Include="..\SchholPortal.Services\SchoolPortal.Services.csproj" />
    <ProjectReference Include="..\Schoolortal.Entities\SchoolPortal.Entities.csproj" />
  </ItemGroup>

</Project>
