// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class StudentCommentDetailsHistory
{
    public Guid Id { get; set; }

    public Guid StudentCommentId { get; set; }

    public Guid StudentGuid { get; set; }

    public Guid ClassId { get; set; }

    public Guid SectionId { get; set; }

    public Guid? Session { get; set; }

    public string Q1Desc { get; set; }

    public string Q2Desc { get; set; }

    public string Q3Desc { get; set; }

    public string SA1Desc { get; set; }

    public string SA2Desc { get; set; }

    public string FinalDesc { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }
}