// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class AuditType
{
    public int ID { get; set; }

    public string Category { get; set; }

    public string Type { get; set; }

    public string Name { get; set; }

    public Guid? SchoolId { get; set; }

    public Guid? CompanyId { get; set; }

    // // public virtual CompanyMaster Company { get; set; }

    // // public virtual SchoolMaster School { get; set; }
}