// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class CityMaster
{
    public Guid Id { get; set; }

    public string CityName { get; set; }

    public Guid CityStateId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual ICollection<AuthorMaster> AuthorMaster { get; set; } = new List<AuthorMaster>();

    // public virtual StateMaster CityState { get; set; }

    // public virtual ICollection<CompanyMaster> CompanyMasterCity { get; set; } = new List<CompanyMaster>();

    // public virtual ICollection<CompanyMaster> CompanyMasterJudistrictionAreaNavigation { get; set; } = new List<CompanyMaster>();

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<DriverMaster> DriverMaster { get; set; } = new List<DriverMaster>();

    // public virtual ICollection<EmpLeaveAvailDetails> EmpLeaveAvailDetails { get; set; } = new List<EmpLeaveAvailDetails>();

    // public virtual ICollection<EmpMaster> EmpMasterCurrentCity { get; set; } = new List<EmpMaster>();

    // public virtual ICollection<EmpMaster> EmpMasterPermanentCity { get; set; } = new List<EmpMaster>();

    // public virtual ICollection<LocationMaster> LocationMaster { get; set; } = new List<LocationMaster>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual ICollection<ParentMaster> ParentMasterCity { get; set; } = new List<ParentMaster>();

    // public virtual ICollection<ParentMaster> ParentMasterOfficeCity { get; set; } = new List<ParentMaster>();

    // public virtual ICollection<PublisherMaster> PublisherMaster { get; set; } = new List<PublisherMaster>();

    // public virtual ICollection<RegistrationMaster> RegistrationMaster { get; set; } = new List<RegistrationMaster>();

    // public virtual ICollection<RouteLocationMaster> RouteLocationMaster { get; set; } = new List<RouteLocationMaster>();

    // public virtual ICollection<SchoolContactMaster> SchoolContactMaster { get; set; } = new List<SchoolContactMaster>();

    // public virtual ICollection<SchoolMaster> SchoolMasterBankCity { get; set; } = new List<SchoolMaster>();

    // public virtual ICollection<SchoolMaster> SchoolMasterCity { get; set; } = new List<SchoolMaster>();

    // public virtual ICollection<SchoolMaster> SchoolMasterJudistrictionCity { get; set; } = new List<SchoolMaster>();

    // public virtual ICollection<StudentMaster> StudentMasterBirthCity { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentMaster> StudentMasterCity { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistoryBirthCity { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistoryCity { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<SupplierMaster> SupplierMaster { get; set; } = new List<SupplierMaster>();

    // public virtual ICollection<TeacherMaster> TeacherMaster { get; set; } = new List<TeacherMaster>();

    // public virtual ICollection<VendorMaster> VendorMaster { get; set; } = new List<VendorMaster>();

    // public virtual ICollection<VisitorMaster> VisitorMaster { get; set; } = new List<VisitorMaster>();
}