// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class CountryMaster
{
    public Guid Id { get; set; }

    public string CountryName { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual ICollection<AuthorMaster> AuthorMaster { get; set; } = new List<AuthorMaster>();

    // public virtual ICollection<CompanyMaster> CompanyMaster { get; set; } = new List<CompanyMaster>();

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<DriverMaster> DriverMaster { get; set; } = new List<DriverMaster>();

    // public virtual ICollection<EmpLeaveAvailDetails> EmpLeaveAvailDetails { get; set; } = new List<EmpLeaveAvailDetails>();

    // public virtual ICollection<EmpMaster> EmpMasterCurrentCountry { get; set; } = new List<EmpMaster>();

    // public virtual ICollection<EmpMaster> EmpMasterPermanentCountry { get; set; } = new List<EmpMaster>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual ICollection<ParentMaster> ParentMasterCountry { get; set; } = new List<ParentMaster>();

    // public virtual ICollection<ParentMaster> ParentMasterOfficeCountry { get; set; } = new List<ParentMaster>();

    // public virtual ICollection<PublisherMaster> PublisherMaster { get; set; } = new List<PublisherMaster>();

    // public virtual ICollection<RegistrationMaster> RegistrationMaster { get; set; } = new List<RegistrationMaster>();

    // public virtual ICollection<SchoolContactMaster> SchoolContactMaster { get; set; } = new List<SchoolContactMaster>();

    // public virtual ICollection<SchoolMaster> SchoolMasterBankCountry { get; set; } = new List<SchoolMaster>();

    // public virtual ICollection<SchoolMaster> SchoolMasterCountry { get; set; } = new List<SchoolMaster>();

    // public virtual ICollection<SchoolMaster> SchoolMasterJudistrictionCountry { get; set; } = new List<SchoolMaster>();

    // public virtual ICollection<StateMaster> StateMaster { get; set; } = new List<StateMaster>();

    // public virtual ICollection<StudentMaster> StudentMasterBirthCountry { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentMaster> StudentMasterCountry { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistoryBirthCountry { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistoryCountry { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistoryNationalityNavigation { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<StudentMaster> StudentMasterNationalityNavigation { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<SupplierMaster> SupplierMaster { get; set; } = new List<SupplierMaster>();

    // public virtual ICollection<TeacherMaster> TeacherMaster { get; set; } = new List<TeacherMaster>();

    // public virtual ICollection<VendorMaster> VendorMaster { get; set; } = new List<VendorMaster>();

    // public virtual ICollection<VisitorMaster> VisitorMaster { get; set; } = new List<VisitorMaster>();
}