// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class DesignationGrade
{
    public Guid Id { get; set; }

    public string Grade { get; set; }

    public string Details { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<EmpSalaryDetails> EmpSalaryDetails { get; set; } = new List<EmpSalaryDetails>();

    // public virtual ICollection<EmpSalaryDetailsHistory> EmpSalaryDetailsHistory { get; set; } = new List<EmpSalaryDetailsHistory>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }
}