// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class EmpCategoryMaster
{
    public Guid Id { get; set; }

    public string CategoryName { get; set; }

    public string CategoryDescription { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual EmpCategoryMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<EmpLeaveDetails> EmpLeaveDetails { get; set; } = new List<EmpLeaveDetails>();

    // public virtual ICollection<EmpLeaveDetailsHistory> EmpLeaveDetailsHistory { get; set; } = new List<EmpLeaveDetailsHistory>();

    // public virtual ICollection<EmpMaster> EmpMasterCategory { get; set; } = new List<EmpMaster>();

    // public virtual ICollection<EmpMaster> EmpMasterEmployeeCategory { get; set; } = new List<EmpMaster>();

    // public virtual ICollection<EmpCategoryMaster> InverseCompany { get; set; } = new List<EmpCategoryMaster>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual SchoolMaster School { get; set; }
}