// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class EmpCatLeaveDetailsHistory
{
    public Guid Id { get; set; }

    public Guid EmpCatLeaveCategoryId { get; set; }

    public Guid LeaveTypeId { get; set; }

    public decimal? TotalLeaves { get; set; }

    public Guid Session { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual LeaveTypeMaster EmpCatLeaveCategory { get; set; }

    // public virtual LeaveTypeMaster LeaveType { get; set; }

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual SchoolMaster School { get; set; }

    // public virtual SessionMaster SessionNavigation { get; set; }
}