// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class ErrorType
{
    public Guid ID { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    // public virtual ICollection<Error> Error { get; set; } = new List<Error>();

    // public virtual SchoolMaster School { get; set; }
}