// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class ErrorDetail
{
    public Guid Id { get; set; }

    public Guid ErrorID { get; set; }

    public string Details { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual Error Error { get; set; }

    // public virtual SchoolMaster School { get; set; }
}