// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class Error
{
    public Guid ID { get; set; }

    public Guid UserID { get; set; }

    public DateTime Timestamp { get; set; }

    public Guid? ErrorTypeID { get; set; }

    public string ActiveForm { get; set; }

    public string Message { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public DateTime ServerTimeStamp { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual ICollection<ErrorDetail> ErrorDetail { get; set; } = new List<ErrorDetail>();

    // public virtual ErrorType ErrorType { get; set; }

    // public virtual SchoolMaster School { get; set; }

    // public virtual UserDetails User { get; set; }
}