// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class GenderMaster
{
    public Guid Id { get; set; }

    public string Gender { get; set; }

    public bool IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<EmpMaster> EmpMaster { get; set; } = new List<EmpMaster>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual ICollection<RegistrationMaster> RegistrationMaster { get; set; } = new List<RegistrationMaster>();

    // public virtual ICollection<StudentMaster> StudentMaster { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistory { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<TeacherMaster> TeacherMaster { get; set; } = new List<TeacherMaster>();
}