// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class ItemLocationMaster
{
    public Guid Id { get; set; }

    public string LocationName { get; set; }

    public string Description { get; set; }

    public string Building { get; set; }

    public string LocationFloor { get; set; }

    public int? LocationNumber { get; set; }

    public int? Capacity { get; set; }

    public bool? IsActive { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<InventoryMaster> InventoryMaster { get; set; } = new List<InventoryMaster>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual SchoolMaster School { get; set; }
}