// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class LeaveTypeMaster
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public Guid? ApplicableGender { get; set; }

    public bool IsSpecialLeave { get; set; }

    public bool IsEncashable { get; set; }

    public bool IsCarryForward { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<EmpAttendanceDetails> EmpAttendanceDetails { get; set; } = new List<EmpAttendanceDetails>();

    // public virtual ICollection<EmpAttendanceDetailsHistory> EmpAttendanceDetailsHistory { get; set; } = new List<EmpAttendanceDetailsHistory>();

    // public virtual ICollection<EmpCatLeaveDetails> EmpCatLeaveDetailsEmpCatLeaveCategory { get; set; } = new List<EmpCatLeaveDetails>();

    // public virtual ICollection<EmpCatLeaveDetailsHistory> EmpCatLeaveDetailsHistoryEmpCatLeaveCategory { get; set; } = new List<EmpCatLeaveDetailsHistory>();

    // public virtual ICollection<EmpCatLeaveDetailsHistory> EmpCatLeaveDetailsHistoryLeaveType { get; set; } = new List<EmpCatLeaveDetailsHistory>();

    // public virtual ICollection<EmpCatLeaveDetails> EmpCatLeaveDetailsLeaveType { get; set; } = new List<EmpCatLeaveDetails>();

    // public virtual ICollection<EmpLeaveAvailDetails> EmpLeaveAvailDetails { get; set; } = new List<EmpLeaveAvailDetails>();

    // public virtual ICollection<EmpLeaveDetails> EmpLeaveDetails { get; set; } = new List<EmpLeaveDetails>();

    // public virtual ICollection<EmpLeaveDetailsHistory> EmpLeaveDetailsHistory { get; set; } = new List<EmpLeaveDetailsHistory>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual SchoolMaster School { get; set; }
}