// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class RouteMaster
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public Guid? SessionId { get; set; }

    public Guid StartLocationId { get; set; }

    public Guid EndLocationId { get; set; }

    public Guid ApplicableClasses { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual RouteLocationMaster EndLocation { get; set; }

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual ICollection<RouteDetails> RouteDetails { get; set; } = new List<RouteDetails>();

    // public virtual ICollection<RouteStopDetails> RouteStopDetails { get; set; } = new List<RouteStopDetails>();

    // public virtual SchoolMaster School { get; set; }

    // public virtual SessionMaster Session { get; set; }

    // public virtual RouteLocationMaster StartLocation { get; set; }

    // public virtual ICollection<StudentMaster> StudentMaster { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistory { get; set; } = new List<StudentMasterHistory>();
}