// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class RouteDetails
{
    public Guid Id { get; set; }

    public Guid RouteId { get; set; }

    public Guid VehicleId { get; set; }

    public Guid DriverId { get; set; }

    public Guid CleanerId { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual CleanerMaster Cleaner { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual DriverMaster Driver { get; set; }

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual RouteMaster Route { get; set; }

    // public virtual ICollection<RouteStopDetails> RouteStopDetails { get; set; } = new List<RouteStopDetails>();

    // public virtual SchoolMaster School { get; set; }

    // public virtual VehicleMaster Vehicle { get; set; }
}