// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class SalaryHeadMaster
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public bool? IsReadOnly { get; set; }

    public Guid SalaryTypeId { get; set; }

    public bool IsDeduction { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    public Guid? SchoolId { get; set; }

    public Guid? CompanyId { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<EmpSalaryDetails> EmpSalaryDetails { get; set; } = new List<EmpSalaryDetails>();

    // public virtual ICollection<EmpSalaryDetailsHistory> EmpSalaryDetailsHistory { get; set; } = new List<EmpSalaryDetailsHistory>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual SalaryTypeMaster SalaryType { get; set; }

    // public virtual SchoolMaster School { get; set; }
}