// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class ScholasticMaster
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Guid? ParentId { get; set; }

    public Guid? SubjectId { get; set; }

    public Guid? CompanyId { get; set; }

    public Guid? SchoolId { get; set; }

    public Guid? SessionId { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual ICollection<ClassScholasticDetail> ClassScholasticDetail { get; set; } = new List<ClassScholasticDetail>();

    // public virtual ICollection<ClassScholasticDetailHistory> ClassScholasticDetailHistory { get; set; } = new List<ClassScholasticDetailHistory>();

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual ParentMaster Parent { get; set; }

    // public virtual SchoolMaster School { get; set; }

    // public virtual SessionMaster Session { get; set; }

    // public virtual ICollection<StudentGradeDetailsHistory> StudentGradeDetailsHistory { get; set; } = new List<StudentGradeDetailsHistory>();

    // public virtual SubjectMaster Subject { get; set; }
}