// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class SchoolMaster
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Email { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public Guid? CityId { get; set; }

    public Guid? StateId { get; set; }

    public Guid? CountryId { get; set; }

    public string ZipCode { get; set; }

    public string Phone { get; set; }

    public string EstablishmentYear { get; set; }

    public string Mobile { get; set; }

    public Guid? JudistrictionCityId { get; set; }

    public Guid? JudistrictionStateId { get; set; }

    public Guid? JudistrictionCountryId { get; set; }

    public string BankName { get; set; }

    public string BankAddress1 { get; set; }

    public string BankAddress2 { get; set; }

    public Guid? BankCityId { get; set; }

    public Guid? BankStateId { get; set; }

    public Guid? BankCountryId { get; set; }

    public string BankZipCode { get; set; }

    public string AccountNumber { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CompanyId { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual ICollection<AssesmentMaster> AssesmentMaster { get; set; } = new List<AssesmentMaster>();

    // public virtual ICollection<AttendanceReasonMaster> AttendanceReasonMaster { get; set; } = new List<AttendanceReasonMaster>();

    // public virtual ICollection<Audit> Audit { get; set; } = new List<Audit>();

    // public virtual ICollection<AuditType> AuditType { get; set; } = new List<AuditType>();

    // public virtual ICollection<AuthorMaster> AuthorMaster { get; set; } = new List<AuthorMaster>();

    // public virtual CityMaster BankCity { get; set; }

    // public virtual CountryMaster BankCountry { get; set; }

    // public virtual StateMaster BankState { get; set; }

    // public virtual ICollection<BillDetails> BillDetails { get; set; } = new List<BillDetails>();

    // public virtual ICollection<BillMaster> BillMaster { get; set; } = new List<BillMaster>();

    // public virtual ICollection<BookCategoryMaster> BookCategoryMaster { get; set; } = new List<BookCategoryMaster>();

    // public virtual ICollection<BookMaster> BookMaster { get; set; } = new List<BookMaster>();

    // public virtual ICollection<BookTransactionDetails> BookTransactionDetails { get; set; } = new List<BookTransactionDetails>();

    // public virtual ICollection<BookTransactionType> BookTransactionType { get; set; } = new List<BookTransactionType>();

    // public virtual ICollection<BookTypeMaster> BookTypeMaster { get; set; } = new List<BookTypeMaster>();

    // public virtual CityMaster City { get; set; }

    // public virtual ICollection<ClassMaster> ClassMaster { get; set; } = new List<ClassMaster>();

    // public virtual ICollection<ClassSMSTasksDetails> ClassSMSTasksDetails { get; set; } = new List<ClassSMSTasksDetails>();

    // public virtual ICollection<ClassScholasticDetail> ClassScholasticDetail { get; set; } = new List<ClassScholasticDetail>();

    // public virtual ICollection<ClassScholasticDetailHistory> ClassScholasticDetailHistory { get; set; } = new List<ClassScholasticDetailHistory>();

    // public virtual ICollection<ClassSectionDetail> ClassSectionDetail { get; set; } = new List<ClassSectionDetail>();

    // public virtual ICollection<ClassSubjectDetail> ClassSubjectDetail { get; set; } = new List<ClassSubjectDetail>();

    // public virtual ICollection<ClassSubjectDetailHistory> ClassSubjectDetailHistory { get; set; } = new List<ClassSubjectDetailHistory>();

    // public virtual ICollection<CleanerMaster> CleanerMaster { get; set; } = new List<CleanerMaster>();

    // public virtual CountryMaster Country { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<DeptDesigDetails> DeptDesigDetails { get; set; } = new List<DeptDesigDetails>();

    // public virtual ICollection<DeptMaster> DeptMaster { get; set; } = new List<DeptMaster>();

    // public virtual ICollection<DesigGradeDetails> DesigGradeDetails { get; set; } = new List<DesigGradeDetails>();

    // public virtual ICollection<DesigMaster> DesigMaster { get; set; } = new List<DesigMaster>();

    // public virtual ICollection<DriverMaster> DriverMaster { get; set; } = new List<DriverMaster>();

    // public virtual ICollection<EmpAttendanceDetails> EmpAttendanceDetails { get; set; } = new List<EmpAttendanceDetails>();

    // public virtual ICollection<EmpAttendanceDetailsHistory> EmpAttendanceDetailsHistory { get; set; } = new List<EmpAttendanceDetailsHistory>();

    // public virtual ICollection<EmpCatLeaveDetails> EmpCatLeaveDetails { get; set; } = new List<EmpCatLeaveDetails>();

    // public virtual ICollection<EmpCatLeaveDetailsHistory> EmpCatLeaveDetailsHistory { get; set; } = new List<EmpCatLeaveDetailsHistory>();

    // public virtual ICollection<EmpCategoryMaster> EmpCategoryMaster { get; set; } = new List<EmpCategoryMaster>();

    // public virtual ICollection<EmpDocumentDetails> EmpDocumentDetails { get; set; } = new List<EmpDocumentDetails>();

    // public virtual ICollection<EmpLeaveAvailDetails> EmpLeaveAvailDetails { get; set; } = new List<EmpLeaveAvailDetails>();

    // public virtual ICollection<EmpLeaveDetails> EmpLeaveDetails { get; set; } = new List<EmpLeaveDetails>();

    // public virtual ICollection<EmpLeaveDetailsHistory> EmpLeaveDetailsHistory { get; set; } = new List<EmpLeaveDetailsHistory>();

    // public virtual ICollection<EmpMaster> EmpMaster { get; set; } = new List<EmpMaster>();

    // public virtual ICollection<EmpProfQualiDetails> EmpProfQualiDetails { get; set; } = new List<EmpProfQualiDetails>();

    // public virtual ICollection<EmpSalaryDetails> EmpSalaryDetails { get; set; } = new List<EmpSalaryDetails>();

    // public virtual ICollection<EmpSalaryDetailsHistory> EmpSalaryDetailsHistory { get; set; } = new List<EmpSalaryDetailsHistory>();

    // public virtual ICollection<EmpSalaryMaster> EmpSalaryMaster { get; set; } = new List<EmpSalaryMaster>();

    // public virtual ICollection<EmpSalaryMasterHistory> EmpSalaryMasterHistory { get; set; } = new List<EmpSalaryMasterHistory>();

    // public virtual ICollection<EmpSalaryStructureDetails> EmpSalaryStructureDetails { get; set; } = new List<EmpSalaryStructureDetails>();

    // public virtual ICollection<EmpSalaryStructureDetailsHistory> EmpSalaryStructureDetailsHistory { get; set; } = new List<EmpSalaryStructureDetailsHistory>();

    // public virtual ICollection<EmpTypeMaster> EmpTypeMaster { get; set; } = new List<EmpTypeMaster>();

    // public virtual ICollection<Error> Error { get; set; } = new List<Error>();

    // public virtual ICollection<ErrorDetail> ErrorDetail { get; set; } = new List<ErrorDetail>();

    // public virtual ICollection<ErrorType> ErrorType { get; set; } = new List<ErrorType>();

    // public virtual ICollection<ExamCategoryMaster> ExamCategoryMaster { get; set; } = new List<ExamCategoryMaster>();

    // public virtual ICollection<ExamUnitMaster> ExamUnitMaster { get; set; } = new List<ExamUnitMaster>();

    // public virtual ICollection<ExpenseCategoryMaster> ExpenseCategoryMaster { get; set; } = new List<ExpenseCategoryMaster>();

    // public virtual ICollection<FeesDiscountCategoryMaster> FeesDiscountCategoryMaster { get; set; } = new List<FeesDiscountCategoryMaster>();

    // public virtual ICollection<GradeMaster> GradeMaster { get; set; } = new List<GradeMaster>();

    // public virtual ICollection<HolidayClassDetails> HolidayClassDetails { get; set; } = new List<HolidayClassDetails>();

    // public virtual ICollection<HolidayDeptDetails> HolidayDeptDetails { get; set; } = new List<HolidayDeptDetails>();

    // public virtual ICollection<HolidayMaster> HolidayMaster { get; set; } = new List<HolidayMaster>();

    // public virtual ICollection<HolidayTypeMaster> HolidayTypeMaster { get; set; } = new List<HolidayTypeMaster>();

    // public virtual ICollection<HouseMaster> HouseMaster { get; set; } = new List<HouseMaster>();

    // public virtual ICollection<InventoryMaster> InventoryMaster { get; set; } = new List<InventoryMaster>();

    // public virtual ICollection<ItemLocationMaster> ItemLocationMaster { get; set; } = new List<ItemLocationMaster>();

    // public virtual ICollection<ItemMaster> ItemMaster { get; set; } = new List<ItemMaster>();

    // public virtual ICollection<ItemTypeMaster> ItemTypeMaster { get; set; } = new List<ItemTypeMaster>();

    // public virtual CityMaster JudistrictionCity { get; set; }

    // public virtual CountryMaster JudistrictionCountry { get; set; }

    // public virtual StateMaster JudistrictionState { get; set; }

    // public virtual ICollection<LeaveStatusMaster> LeaveStatusMaster { get; set; } = new List<LeaveStatusMaster>();

    // public virtual ICollection<LeaveTypeMaster> LeaveTypeMaster { get; set; } = new List<LeaveTypeMaster>();

    // public virtual ICollection<LocationMaster> LocationMaster { get; set; } = new List<LocationMaster>();

    // public virtual ICollection<MaritalStatus> MaritalStatus { get; set; } = new List<MaritalStatus>();

    // public virtual ICollection<MarksGradeMaster> MarksGradeMaster { get; set; } = new List<MarksGradeMaster>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual ICollection<NotificationReceiverMaster> NotificationReceiverMaster { get; set; } = new List<NotificationReceiverMaster>();

    // public virtual ICollection<ParentMaster> ParentMaster { get; set; } = new List<ParentMaster>();

    // public virtual ICollection<PaymentModeMaster> PaymentModeMaster { get; set; } = new List<PaymentModeMaster>();

    // public virtual ICollection<ProfessionMaster> ProfessionMaster { get; set; } = new List<ProfessionMaster>();

    // public virtual ICollection<PublisherMaster> PublisherMaster { get; set; } = new List<PublisherMaster>();

    // public virtual ICollection<RegistrationMaster> RegistrationMaster { get; set; } = new List<RegistrationMaster>();

    // public virtual ICollection<RoleMaster> RoleMaster { get; set; } = new List<RoleMaster>();

    // public virtual ICollection<RouteDetails> RouteDetails { get; set; } = new List<RouteDetails>();

    // public virtual ICollection<RouteLocationMaster> RouteLocationMaster { get; set; } = new List<RouteLocationMaster>();

    // public virtual ICollection<RouteMaster> RouteMaster { get; set; } = new List<RouteMaster>();

    // public virtual ICollection<RouteStopDetails> RouteStopDetails { get; set; } = new List<RouteStopDetails>();

    // public virtual ICollection<SMSTask> SMSTask { get; set; } = new List<SMSTask>();

    // public virtual ICollection<SalaryCode> SalaryCode { get; set; } = new List<SalaryCode>();

    // public virtual ICollection<SalaryDesigGradeDetails> SalaryDesigGradeDetails { get; set; } = new List<SalaryDesigGradeDetails>();

    // public virtual ICollection<SalaryDesigGradeDetailsHistory> SalaryDesigGradeDetailsHistory { get; set; } = new List<SalaryDesigGradeDetailsHistory>();

    // public virtual ICollection<SalaryHeadMaster> SalaryHeadMaster { get; set; } = new List<SalaryHeadMaster>();

    // public virtual ICollection<SalaryType> SalaryType { get; set; } = new List<SalaryType>();

    // public virtual ICollection<SalaryTypeMaster> SalaryTypeMaster { get; set; } = new List<SalaryTypeMaster>();

    // public virtual ICollection<ScholasticMaster> ScholasticMaster { get; set; } = new List<ScholasticMaster>();

    // public virtual ICollection<ScholasticUnitDetail> ScholasticUnitDetail { get; set; } = new List<ScholasticUnitDetail>();

    // public virtual ICollection<SchoolContactMaster> SchoolContactMaster { get; set; } = new List<SchoolContactMaster>();

    // public virtual StateMaster State { get; set; }

    // public virtual ICollection<StudentCommentDetailsHistory> StudentCommentDetailsHistory { get; set; } = new List<StudentCommentDetailsHistory>();

    // public virtual ICollection<StudentFeeDetails> StudentFeeDetails { get; set; } = new List<StudentFeeDetails>();

    // public virtual ICollection<StudentFeeDetailsHistory> StudentFeeDetailsHistory { get; set; } = new List<StudentFeeDetailsHistory>();

    // public virtual ICollection<StudentGradeDetails> StudentGradeDetails { get; set; } = new List<StudentGradeDetails>();

    // public virtual ICollection<StudentGradeDetailsHistory> StudentGradeDetailsHistory { get; set; } = new List<StudentGradeDetailsHistory>();

    // public virtual ICollection<StudentMarksDetails> StudentMarksDetails { get; set; } = new List<StudentMarksDetails>();

    // public virtual ICollection<StudentMarksDetailsHistory> StudentMarksDetailsHistory { get; set; } = new List<StudentMarksDetailsHistory>();

    // public virtual ICollection<StudentMaster> StudentMaster { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistory { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<StudentReportCardDetails> StudentReportCardDetails { get; set; } = new List<StudentReportCardDetails>();

    // public virtual ICollection<StudentReportCardDetailsHistory> StudentReportCardDetailsHistory { get; set; } = new List<StudentReportCardDetailsHistory>();

    // public virtual ICollection<StudentReportCardMaster> StudentReportCardMaster { get; set; } = new List<StudentReportCardMaster>();

    // public virtual ICollection<StudentReportCardMasterHistory> StudentReportCardMasterHistory { get; set; } = new List<StudentReportCardMasterHistory>();

    // public virtual ICollection<SubjectCategoryDetails> SubjectCategoryDetails { get; set; } = new List<SubjectCategoryDetails>();

    // public virtual ICollection<SubjectCategoryDetailsHistory> SubjectCategoryDetailsHistory { get; set; } = new List<SubjectCategoryDetailsHistory>();

    // public virtual ICollection<SubjectMaster> SubjectMaster { get; set; } = new List<SubjectMaster>();

    // public virtual ICollection<SupplierMaster> SupplierMaster { get; set; } = new List<SupplierMaster>();

    // public virtual ICollection<SystemParameters> SystemParameters { get; set; } = new List<SystemParameters>();

    // public virtual ICollection<TeacherClassDetails> TeacherClassDetails { get; set; } = new List<TeacherClassDetails>();

    // public virtual ICollection<TeacherDocumentDetails> TeacherDocumentDetails { get; set; } = new List<TeacherDocumentDetails>();

    // public virtual ICollection<TeacherMaster> TeacherMaster { get; set; } = new List<TeacherMaster>();

    // public virtual ICollection<TeacherQualificationDetails> TeacherQualificationDetails { get; set; } = new List<TeacherQualificationDetails>();

    // public virtual ICollection<TeacherSectionDetails> TeacherSectionDetails { get; set; } = new List<TeacherSectionDetails>();

    // public virtual ICollection<TeacherSubjectDetails> TeacherSubjectDetails { get; set; } = new List<TeacherSubjectDetails>();

    // public virtual ICollection<TimeTableClassPeriodDetails> TimeTableClassPeriodDetails { get; set; } = new List<TimeTableClassPeriodDetails>();

    // public virtual ICollection<TimeTableClassPeriodDetailsHistory> TimeTableClassPeriodDetailsHistory { get; set; } = new List<TimeTableClassPeriodDetailsHistory>();

    // public virtual ICollection<TimeTableDetailsHistory> TimeTableDetailsHistory { get; set; } = new List<TimeTableDetailsHistory>();

    // public virtual ICollection<TimeTablePeriodMaster> TimeTablePeriodMaster { get; set; } = new List<TimeTablePeriodMaster>();

    // public virtual ICollection<TimeTableSessions> TimeTableSessions { get; set; } = new List<TimeTableSessions>();

    // public virtual ICollection<TimeTableSetupDetails> TimeTableSetupDetails { get; set; } = new List<TimeTableSetupDetails>();

    // public virtual ICollection<TimeTableSetupDetailsHistory> TimeTableSetupDetailsHistory { get; set; } = new List<TimeTableSetupDetailsHistory>();

    // public virtual ICollection<TimeTableSubstitutionDetails> TimeTableSubstitutionDetails { get; set; } = new List<TimeTableSubstitutionDetails>();

    // public virtual ICollection<TimeTableSubstitutionDetailsHistory> TimeTableSubstitutionDetailsHistory { get; set; } = new List<TimeTableSubstitutionDetailsHistory>();

    // public virtual ICollection<UserDetails> UserDetails { get; set; } = new List<UserDetails>();

    // public virtual ICollection<VehicleExpenseDetails> VehicleExpenseDetails { get; set; } = new List<VehicleExpenseDetails>();

    // public virtual ICollection<VehicleMaster> VehicleMaster { get; set; } = new List<VehicleMaster>();

    // public virtual ICollection<VehicleTypeMaster> VehicleTypeMaster { get; set; } = new List<VehicleTypeMaster>();

    // public virtual ICollection<VendorMaster> VendorMaster { get; set; } = new List<VendorMaster>();

    // public virtual ICollection<VisitorMaster> VisitorMaster { get; set; } = new List<VisitorMaster>();

    // public virtual ICollection<VoucherMaster> VoucherMaster { get; set; } = new List<VoucherMaster>();
}