// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class SectionMaster
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual ICollection<BookTransactionDetails> BookTransactionDetails { get; set; } = new List<BookTransactionDetails>();

    // public virtual ICollection<ClassSMSTasksDetails> ClassSMSTasksDetails { get; set; } = new List<ClassSMSTasksDetails>();

    // public virtual ICollection<ClassSectionDetail> ClassSectionDetail { get; set; } = new List<ClassSectionDetail>();

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<HolidayClassDetails> HolidayClassDetails { get; set; } = new List<HolidayClassDetails>();

    // public virtual ICollection<SectionMaster> InverseSchool { get; set; } = new List<SectionMaster>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual SectionMaster School { get; set; }

    // public virtual ICollection<StudentAttendanceDetails> StudentAttendanceDetails { get; set; } = new List<StudentAttendanceDetails>();

    // public virtual ICollection<StudentCommentDetails> StudentCommentDetails { get; set; } = new List<StudentCommentDetails>();

    // public virtual ICollection<StudentCommentDetailsHistory> StudentCommentDetailsHistory { get; set; } = new List<StudentCommentDetailsHistory>();

    // public virtual ICollection<StudentFeeDetails> StudentFeeDetails { get; set; } = new List<StudentFeeDetails>();

    // public virtual ICollection<StudentFeeDetailsHistory> StudentFeeDetailsHistory { get; set; } = new List<StudentFeeDetailsHistory>();

    // public virtual ICollection<StudentGradeDetails> StudentGradeDetails { get; set; } = new List<StudentGradeDetails>();

    // public virtual ICollection<StudentGradeDetailsHistory> StudentGradeDetailsHistory { get; set; } = new List<StudentGradeDetailsHistory>();

    // public virtual ICollection<StudentMarksDetails> StudentMarksDetails { get; set; } = new List<StudentMarksDetails>();

    // public virtual ICollection<StudentMarksDetailsHistory> StudentMarksDetailsHistory { get; set; } = new List<StudentMarksDetailsHistory>();

    // public virtual ICollection<StudentMaster> StudentMaster { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistory { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<StudentReportCardMaster> StudentReportCardMaster { get; set; } = new List<StudentReportCardMaster>();

    // public virtual ICollection<StudentReportCardMasterHistory> StudentReportCardMasterHistory { get; set; } = new List<StudentReportCardMasterHistory>();

    // public virtual ICollection<TeacherClassDetails> TeacherClassDetails { get; set; } = new List<TeacherClassDetails>();

    // public virtual ICollection<TeacherSectionDetails> TeacherSectionDetails { get; set; } = new List<TeacherSectionDetails>();

    // public virtual ICollection<TimeTableClassPeriodDetails> TimeTableClassPeriodDetails { get; set; } = new List<TimeTableClassPeriodDetails>();

    // public virtual ICollection<TimeTableClassPeriodDetailsHistory> TimeTableClassPeriodDetailsHistory { get; set; } = new List<TimeTableClassPeriodDetailsHistory>();

    // public virtual ICollection<TimeTableDetailsHistory> TimeTableDetailsHistory { get; set; } = new List<TimeTableDetailsHistory>();

    // public virtual ICollection<TimeTableSubstitutionDetails> TimeTableSubstitutionDetails { get; set; } = new List<TimeTableSubstitutionDetails>();

    // public virtual ICollection<TimeTableSubstitutionDetailsHistory> TimeTableSubstitutionDetailsHistory { get; set; } = new List<TimeTableSubstitutionDetailsHistory>();
}