// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class SessionMaster
{
    public Guid Id { get; set; }

    public string Value { get; set; }

    public string Description { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual ICollection<ClassScholasticDetailHistory> ClassScholasticDetailHistory { get; set; } = new List<ClassScholasticDetailHistory>();

    // public virtual ICollection<ClassSubjectDetailHistory> ClassSubjectDetailHistory { get; set; } = new List<ClassSubjectDetailHistory>();

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<EmpCatLeaveDetails> EmpCatLeaveDetails { get; set; } = new List<EmpCatLeaveDetails>();

    // public virtual ICollection<EmpCatLeaveDetailsHistory> EmpCatLeaveDetailsHistory { get; set; } = new List<EmpCatLeaveDetailsHistory>();

    // public virtual ICollection<EmpLeaveAvailDetails> EmpLeaveAvailDetails { get; set; } = new List<EmpLeaveAvailDetails>();

    // public virtual ICollection<EmpLeaveDetails> EmpLeaveDetails { get; set; } = new List<EmpLeaveDetails>();

    // public virtual ICollection<EmpLeaveDetailsHistory> EmpLeaveDetailsHistory { get; set; } = new List<EmpLeaveDetailsHistory>();

    // public virtual ICollection<EmpSalaryMaster> EmpSalaryMaster { get; set; } = new List<EmpSalaryMaster>();

    // public virtual ICollection<EmpSalaryMasterHistory> EmpSalaryMasterHistory { get; set; } = new List<EmpSalaryMasterHistory>();

    // public virtual ICollection<EmpSalaryStructureDetails> EmpSalaryStructureDetails { get; set; } = new List<EmpSalaryStructureDetails>();

    // public virtual ICollection<EmpSalaryStructureDetailsHistory> EmpSalaryStructureDetailsHistory { get; set; } = new List<EmpSalaryStructureDetailsHistory>();

    // public virtual ICollection<HolidayMaster> HolidayMaster { get; set; } = new List<HolidayMaster>();

    // public virtual ICollection<SessionMaster> InverseSchool { get; set; } = new List<SessionMaster>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual ICollection<RegistrationMaster> RegistrationMaster { get; set; } = new List<RegistrationMaster>();

    // public virtual ICollection<RouteMaster> RouteMaster { get; set; } = new List<RouteMaster>();

    // public virtual ICollection<SalaryDesigGradeDetails> SalaryDesigGradeDetails { get; set; } = new List<SalaryDesigGradeDetails>();

    // public virtual ICollection<SalaryDesigGradeDetailsHistory> SalaryDesigGradeDetailsHistory { get; set; } = new List<SalaryDesigGradeDetailsHistory>();

    // public virtual ICollection<ScholasticMaster> ScholasticMaster { get; set; } = new List<ScholasticMaster>();

    // public virtual SessionMaster School { get; set; }

    // public virtual ICollection<StudentCommentDetails> StudentCommentDetails { get; set; } = new List<StudentCommentDetails>();

    // public virtual ICollection<StudentGradeDetails> StudentGradeDetails { get; set; } = new List<StudentGradeDetails>();

    // public virtual ICollection<StudentGradeDetailsHistory> StudentGradeDetailsHistory { get; set; } = new List<StudentGradeDetailsHistory>();

    // public virtual ICollection<StudentMaster> StudentMaster { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistory { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<StudentReportCardMaster> StudentReportCardMaster { get; set; } = new List<StudentReportCardMaster>();

    // public virtual ICollection<StudentReportCardMasterHistory> StudentReportCardMasterHistory { get; set; } = new List<StudentReportCardMasterHistory>();

    // public virtual ICollection<SubjectCategoryDetails> SubjectCategoryDetails { get; set; } = new List<SubjectCategoryDetails>();

    // public virtual ICollection<SubjectCategoryDetailsHistory> SubjectCategoryDetailsHistory { get; set; } = new List<SubjectCategoryDetailsHistory>();

    // public virtual ICollection<TimeTableClassPeriodDetails> TimeTableClassPeriodDetails { get; set; } = new List<TimeTableClassPeriodDetails>();

    // public virtual ICollection<TimeTableClassPeriodDetailsHistory> TimeTableClassPeriodDetailsHistory { get; set; } = new List<TimeTableClassPeriodDetailsHistory>();

    // public virtual ICollection<TimeTableDetailsHistory> TimeTableDetailsHistory { get; set; } = new List<TimeTableDetailsHistory>();

    // public virtual ICollection<TimeTablePeriodMaster> TimeTablePeriodMaster { get; set; } = new List<TimeTablePeriodMaster>();

    // public virtual ICollection<TimeTableSetupDetails> TimeTableSetupDetails { get; set; } = new List<TimeTableSetupDetails>();

    // public virtual ICollection<TimeTableSetupDetailsHistory> TimeTableSetupDetailsHistory { get; set; } = new List<TimeTableSetupDetailsHistory>();

    // public virtual ICollection<TimeTableSubstitutionDetails> TimeTableSubstitutionDetails { get; set; } = new List<TimeTableSubstitutionDetails>();

    // public virtual ICollection<TimeTableSubstitutionDetailsHistory> TimeTableSubstitutionDetailsHistory { get; set; } = new List<TimeTableSubstitutionDetailsHistory>();
}