// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class SMSTask
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Desctiption { get; set; }

    public bool SendEmail { get; set; }

    public bool SendSMS { get; set; }

    public Guid ReceiverId { get; set; }

    public string RepeatSchedule { get; set; }

    public bool StatusId { get; set; }

    public bool IsActive { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool? IsReadOnly { get; set; }

    public bool? LastRunStatusId { get; set; }

    public DateTime? LastRunDate { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual ICollection<ClassSMSTasksDetails> ClassSMSTasksDetails { get; set; } = new List<ClassSMSTasksDetails>();

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual SchoolMaster School { get; set; }
}