// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class SmtpDetails
{
    public Guid Id { get; set; }

    public string FromAddress { get; set; }

    public string GatewayName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Subject { get; set; }

    public string BodyText { get; set; }

    public string EmailType { get; set; }

    public bool? StatusId { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<SmtpDetails> InverseSchool { get; set; } = new List<SmtpDetails>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual SmtpDetails School { get; set; }
}