// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class StateMaster
{
    public Guid Id { get; set; }

    public string StateName { get; set; }

    public Guid CountryId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual ICollection<AuthorMaster> AuthorMaster { get; set; } = new List<AuthorMaster>();

    // public virtual ICollection<CityMaster> CityMaster { get; set; } = new List<CityMaster>();

    // public virtual ICollection<CompanyMaster> CompanyMaster { get; set; } = new List<CompanyMaster>();

    // public virtual CountryMaster Country { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<DriverMaster> DriverMaster { get; set; } = new List<DriverMaster>();

    // public virtual ICollection<EmpLeaveAvailDetails> EmpLeaveAvailDetails { get; set; } = new List<EmpLeaveAvailDetails>();

    // public virtual ICollection<EmpMaster> EmpMasterCurrentState { get; set; } = new List<EmpMaster>();

    // public virtual ICollection<EmpMaster> EmpMasterPermanentState { get; set; } = new List<EmpMaster>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual ICollection<ParentMaster> ParentMasterOfficeState { get; set; } = new List<ParentMaster>();

    // public virtual ICollection<ParentMaster> ParentMasterState { get; set; } = new List<ParentMaster>();

    // public virtual ICollection<PublisherMaster> PublisherMaster { get; set; } = new List<PublisherMaster>();

    // public virtual ICollection<RegistrationMaster> RegistrationMaster { get; set; } = new List<RegistrationMaster>();

    // public virtual ICollection<SchoolContactMaster> SchoolContactMaster { get; set; } = new List<SchoolContactMaster>();

    // public virtual ICollection<SchoolMaster> SchoolMasterBankState { get; set; } = new List<SchoolMaster>();

    // public virtual ICollection<SchoolMaster> SchoolMasterJudistrictionState { get; set; } = new List<SchoolMaster>();

    // public virtual ICollection<SchoolMaster> SchoolMasterState { get; set; } = new List<SchoolMaster>();

    // public virtual ICollection<StudentMaster> StudentMasterBirthState { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistoryBirthState { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistoryState { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<StudentMaster> StudentMasterState { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<TeacherMaster> TeacherMaster { get; set; } = new List<TeacherMaster>();

    // public virtual ICollection<VendorMaster> VendorMaster { get; set; } = new List<VendorMaster>();
}