// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class StudentGradeDetailsHistory
{
    public Guid Id { get; set; }

    public Guid StudentGUID { get; set; }

    public Guid StudentGradeId { get; set; }

    public Guid ScholisticCategoryId { get; set; }

    public Guid SessionId { get; set; }

    public Guid CategoryId { get; set; }

    public decimal? GradeQ1 { get; set; }

    public decimal? GradeQ2 { get; set; }

    public decimal? GradeQ3 { get; set; }

    public decimal? GradeFA1 { get; set; }

    public decimal? GradeFA2 { get; set; }

    public decimal? GradeFA3 { get; set; }

    public decimal? GradeFA4 { get; set; }

    public decimal? GradeSA1 { get; set; }

    public decimal? GradeSA2 { get; set; }

    public Guid ClassId { get; set; }

    public Guid SectionId { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual CategoryMaster Category { get; set; }

    // public virtual ClassMaster Class { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual ScholasticMaster ScholisticCategory { get; set; }

    // public virtual SchoolMaster School { get; set; }

    // public virtual SectionMaster Section { get; set; }

    // public virtual SessionMaster Session { get; set; }

    // public virtual StudentMaster Student { get; set; }

    // public virtual StudentGradeDetails StudentGrade { get; set; }
}