// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class StudentMaster
{
    public Guid Id { get; set; }

    public Guid RollNumber { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Address { get; set; }

    public Guid CityId { get; set; }

    public Guid StateId { get; set; }

    public Guid CountryId { get; set; }

    public string ZipCode { get; set; }

    public string ContactNumber { get; set; }

    public string EmergencyContactNumber { get; set; }

    public DateTime DOB { get; set; }

    public DateTime DOJ { get; set; }

    public string RegistrationNumber { get; set; }

    public Guid ClassId { get; set; }

    public Guid SectionId { get; set; }

    public bool? AvailTransport { get; set; }

    public string Image { get; set; }

    public string Email { get; set; }

    public Guid CategoryId { get; set; }

    public bool? SiblingsIfAny { get; set; }

    public Guid? SiblingClassId { get; set; }

    public Guid? Gender { get; set; }

    public string DisabilityAny { get; set; }

    public string MedicalAlleryAny { get; set; }

    public Guid BirthCityId { get; set; }

    public Guid BirthStateId { get; set; }

    public Guid BirthCountryId { get; set; }

    public string PreviousSchoolAttended { get; set; }

    public Guid? PreviousSchoolClassId { get; set; }

    public decimal? PreviousSchoolPercentage { get; set; }

    public string PreviousSchoolRank { get; set; }

    public Guid PreviousSchoolBoardId { get; set; }

    public DateTime? PreviousSchoolFromDate { get; set; }

    public DateTime? PreviousSchoolToDate { get; set; }

    public DateTime? WithdrawnDate { get; set; }

    public string WithdrawnReason { get; set; }

    public Guid BloodGroupId { get; set; }

    public Guid Nationality { get; set; }

    public string Hobbies { get; set; }

    public Guid ReligionId { get; set; }

    public string Phone { get; set; }

    public Guid? RouteId { get; set; }

    public Guid? RouteStopDetailsId { get; set; }

    public Guid? ClassTeacherId { get; set; }

    public bool? RoutePickAndDrop { get; set; }

    public Guid? FeesDiscountCategoryMasterId { get; set; }

    public decimal? TutionFees { get; set; }

    public decimal? AnnualFees { get; set; }

    public decimal? TransportFees { get; set; }

    public bool? UseTransportFees { get; set; }

    public Guid? SessionId { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    public Guid? HouseAllotted { get; set; }

    // public virtual CityMaster BirthCity { get; set; }

    // public virtual CountryMaster BirthCountry { get; set; }

    // public virtual StateMaster BirthState { get; set; }

    // public virtual BloodGroupMaster BloodGroup { get; set; }

    // public virtual CategoryMaster Category { get; set; }

    // public virtual CityMaster City { get; set; }

    // public virtual ClassMaster Class { get; set; }

    // public virtual TeacherMaster ClassTeacher { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual CountryMaster Country { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual FeesDiscountCategoryMaster FeesDiscountCategoryMaster { get; set; }

    // public virtual GenderMaster GenderNavigation { get; set; }

    // public virtual HouseMaster HouseAllottedNavigation { get; set; }

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual CountryMaster NationalityNavigation { get; set; }

    // public virtual SchoolBoard PreviousSchoolBoard { get; set; }

    // public virtual ClassMaster PreviousSchoolClass { get; set; }

    // public virtual ReligionMaster Religion { get; set; }

    // public virtual RouteMaster Route { get; set; }

    // public virtual RouteStopDetails RouteStopDetails { get; set; }

    // public virtual SchoolMaster School { get; set; }

    // public virtual SectionMaster Section { get; set; }

    // public virtual SessionMaster Session { get; set; }

    // public virtual ClassMaster SiblingClass { get; set; }

    // public virtual StateMaster State { get; set; }

    // public virtual ICollection<StudentAttendanceDetails> StudentAttendanceDetails { get; set; } = new List<StudentAttendanceDetails>();

    // public virtual ICollection<StudentCommentDetails> StudentCommentDetails { get; set; } = new List<StudentCommentDetails>();

    // public virtual ICollection<StudentCommentDetailsHistory> StudentCommentDetailsHistory { get; set; } = new List<StudentCommentDetailsHistory>();

    // public virtual ICollection<StudentFeeDetails> StudentFeeDetails { get; set; } = new List<StudentFeeDetails>();

    // public virtual ICollection<StudentFeeDetailsHistory> StudentFeeDetailsHistory { get; set; } = new List<StudentFeeDetailsHistory>();

    // public virtual ICollection<StudentGradeDetails> StudentGradeDetails { get; set; } = new List<StudentGradeDetails>();

    // public virtual ICollection<StudentGradeDetailsHistory> StudentGradeDetailsHistory { get; set; } = new List<StudentGradeDetailsHistory>();

    // public virtual ICollection<StudentMarksDetails> StudentMarksDetails { get; set; } = new List<StudentMarksDetails>();

    // public virtual ICollection<StudentMarksDetailsHistory> StudentMarksDetailsHistory { get; set; } = new List<StudentMarksDetailsHistory>();
}