// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class StudentCommentDetails
{
    public Guid Id { get; set; }

    public Guid StudentGUID { get; set; }

    public Guid ClassId { get; set; }

    public Guid SectionId { get; set; }

    public Guid SessionId { get; set; }

    public string DescriptionQtr1 { get; set; }

    public string DescriptionQtr2 { get; set; }

    public string DescriptionQtr3 { get; set; }

    public string DescriptionSA1 { get; set; }

    public string DescriptionSA2 { get; set; }

    public string DescriptionFinal { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual ClassMaster Class { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<StudentCommentDetails> InverseSchool { get; set; } = new List<StudentCommentDetails>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual StudentCommentDetails School { get; set; }

    // public virtual SectionMaster Section { get; set; }

    // public virtual SessionMaster Session { get; set; }

    // public virtual StudentMaster Student { get; set; }

    // public virtual ICollection<StudentCommentDetailsHistory> StudentCommentDetailsHistory { get; set; } = new List<StudentCommentDetailsHistory>();
}