// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class StudentGradeDetails
{
    public Guid Id { get; set; }

    public Guid StudentGUID { get; set; }

    public Guid SessionId { get; set; }

    public Guid CategoryId { get; set; }

    public string GradeQ1 { get; set; }

    public string GradeQ2 { get; set; }

    public string GradeQ3 { get; set; }

    public string GradeFA1 { get; set; }

    public string GradeFA2 { get; set; }

    public string GradeFA3 { get; set; }

    public string GradeFA4 { get; set; }

    public string GradeSA1 { get; set; }

    public string GradeSA2 { get; set; }

    public Guid ClassId { get; set; }

    public Guid SectionId { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }
}