// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class TeacherMaster
{
    public Guid Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime DOB { get; set; }

    public DateTime? DOJ { get; set; }

    public DateTime? DateOfLeaving { get; set; }

    public string Address { get; set; }

    public Guid? CityId { get; set; }

    public Guid? StateId { get; set; }

    public Guid? CountryId { get; set; }

    public string ZipCode { get; set; }

    public Guid? Gender { get; set; }

    public Guid? MaritalStatusId { get; set; }

    public string Image { get; set; }

    public string Phone { get; set; }

    public string MobilePhone { get; set; }

    public string YearsOfExperience { get; set; }

    public string PreviousSchool { get; set; }

    public string Salutation { get; set; }

    public string Email { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual CityMaster City { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual CountryMaster Country { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual GenderMaster GenderNavigation { get; set; }

    // public virtual MaritalStatus MaritalStatus { get; set; }

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual SchoolMaster School { get; set; }

    // public virtual StateMaster State { get; set; }

    // public virtual ICollection<StudentMaster> StudentMaster { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistory { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<TeacherDocumentDetails> TeacherDocumentDetails { get; set; } = new List<TeacherDocumentDetails>();

    // public virtual ICollection<TeacherQualificationDetails> TeacherQualificationDetails { get; set; } = new List<TeacherQualificationDetails>();

    // public virtual ICollection<TeacherSectionDetails> TeacherSectionDetails { get; set; } = new List<TeacherSectionDetails>();

    // public virtual ICollection<TeacherSubjectDetails> TeacherSubjectDetails { get; set; } = new List<TeacherSubjectDetails>();

    // public virtual ICollection<TimeTableDetailsHistory> TimeTableDetailsHistory { get; set; } = new List<TimeTableDetailsHistory>();

    // public virtual ICollection<TimeTableSubstitutionDetailsHistory> TimeTableSubstitutionDetailsHistoryTeacher { get; set; } = new List<TimeTableSubstitutionDetailsHistory>();

    // public virtual ICollection<TimeTableSubstitutionDetailsHistory> TimeTableSubstitutionDetailsHistoryTeacherNew { get; set; } = new List<TimeTableSubstitutionDetailsHistory>();

    // public virtual ICollection<TimeTableSubstitutionDetails> TimeTableSubstitutionDetailsTeacher { get; set; } = new List<TimeTableSubstitutionDetails>();

    // public virtual ICollection<TimeTableSubstitutionDetails> TimeTableSubstitutionDetailsTeacherNew { get; set; } = new List<TimeTableSubstitutionDetails>();
}