// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class TeacherQualificationDetails
{
    public Guid Id { get; set; }

    public Guid TeacherId { get; set; }

    public Guid QualificationId { get; set; }

    public Guid SchoolId { get; set; }

    public Guid CompanyId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual CompanyMaster Company { get; set; }

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual QualificationMaster Qualification { get; set; }

    // public virtual SchoolMaster School { get; set; }

    // public virtual TeacherMaster Teacher { get; set; }
}