// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schoolortal.Entities.Models;

public partial class UserDetails
{
    public Guid Id { get; set; }

    public string UserName { get; set; }

    public string UserPassword { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string EmailAddress { get; set; }

    public Guid DesignationId { get; set; }

    public Guid? UserRoleId { get; set; }

    public bool? IsSuperUser { get; set; }

    public Guid? CompanyId { get; set; }

    public Guid? SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }

    // public virtual ICollection<AssesmentMaster> AssesmentMasterCreatedByNavigation { get; set; } = new List<AssesmentMaster>();

    // public virtual ICollection<AssesmentMaster> AssesmentMasterModifiedByNavigation { get; set; } = new List<AssesmentMaster>();

    // public virtual ICollection<AttendanceReasonMaster> AttendanceReasonMasterCreatedByNavigation { get; set; } = new List<AttendanceReasonMaster>();

    // public virtual ICollection<AttendanceReasonMaster> AttendanceReasonMasterModifiedByNavigation { get; set; } = new List<AttendanceReasonMaster>();

    // public virtual ICollection<Audit> Audit { get; set; } = new List<Audit>();

    // public virtual ICollection<AuthorMaster> AuthorMasterCreatedByNavigation { get; set; } = new List<AuthorMaster>();

    // public virtual ICollection<AuthorMaster> AuthorMasterModifiedByNavigation { get; set; } = new List<AuthorMaster>();

    // public virtual ICollection<BillDetails> BillDetailsCreatedByNavigation { get; set; } = new List<BillDetails>();

    // public virtual ICollection<BillDetails> BillDetailsModifiedByNavigation { get; set; } = new List<BillDetails>();

    // public virtual ICollection<BillMaster> BillMasterCreatedByNavigation { get; set; } = new List<BillMaster>();

    // public virtual ICollection<BillMaster> BillMasterModifiedByNavigation { get; set; } = new List<BillMaster>();

    // public virtual ICollection<BloodGroupMaster> BloodGroupMasterCreatedByNavigation { get; set; } = new List<BloodGroupMaster>();

    // public virtual ICollection<BloodGroupMaster> BloodGroupMasterModifiedByNavigation { get; set; } = new List<BloodGroupMaster>();

    // public virtual ICollection<BookCategoryMaster> BookCategoryMasterCreatedByNavigation { get; set; } = new List<BookCategoryMaster>();

    // public virtual ICollection<BookCategoryMaster> BookCategoryMasterModifiedByNavigation { get; set; } = new List<BookCategoryMaster>();

    // public virtual ICollection<BookMaster> BookMasterCreatedByNavigation { get; set; } = new List<BookMaster>();

    // public virtual ICollection<BookMaster> BookMasterModifiedByNavigation { get; set; } = new List<BookMaster>();

    // public virtual ICollection<BookTransactionDetails> BookTransactionDetailsCreatedByNavigation { get; set; } = new List<BookTransactionDetails>();

    // public virtual ICollection<BookTransactionDetails> BookTransactionDetailsModifiedByNavigation { get; set; } = new List<BookTransactionDetails>();

    // public virtual ICollection<BookTransactionType> BookTransactionTypeCreatedByNavigation { get; set; } = new List<BookTransactionType>();

    // public virtual ICollection<BookTransactionType> BookTransactionTypeModifiedByNavigation { get; set; } = new List<BookTransactionType>();

    // public virtual ICollection<BookTypeMaster> BookTypeMasterCreatedByNavigation { get; set; } = new List<BookTypeMaster>();

    // public virtual ICollection<BookTypeMaster> BookTypeMasterModifiedByNavigation { get; set; } = new List<BookTypeMaster>();

    // public virtual ICollection<CategoryMaster> CategoryMasterCreatedByNavigation { get; set; } = new List<CategoryMaster>();

    // public virtual ICollection<CategoryMaster> CategoryMasterModifiedByNavigation { get; set; } = new List<CategoryMaster>();

    // public virtual ICollection<CityMaster> CityMasterCreatedByNavigation { get; set; } = new List<CityMaster>();

    // public virtual ICollection<CityMaster> CityMasterModifiedByNavigation { get; set; } = new List<CityMaster>();

    // public virtual ICollection<ClassMaster> ClassMasterCreatedByNavigation { get; set; } = new List<ClassMaster>();

    // public virtual ICollection<ClassMaster> ClassMasterModifiedByNavigation { get; set; } = new List<ClassMaster>();

    // public virtual ICollection<ClassSMSTasksDetails> ClassSMSTasksDetailsCreatedByNavigation { get; set; } = new List<ClassSMSTasksDetails>();

    // public virtual ICollection<ClassSMSTasksDetails> ClassSMSTasksDetailsModifiedByNavigation { get; set; } = new List<ClassSMSTasksDetails>();

    // public virtual ICollection<ClassScholasticDetail> ClassScholasticDetailCreatedByNavigation { get; set; } = new List<ClassScholasticDetail>();

    // public virtual ICollection<ClassScholasticDetailHistory> ClassScholasticDetailHistoryCreatedByNavigation { get; set; } = new List<ClassScholasticDetailHistory>();

    // public virtual ICollection<ClassScholasticDetailHistory> ClassScholasticDetailHistoryModifiedByNavigation { get; set; } = new List<ClassScholasticDetailHistory>();

    // public virtual ICollection<ClassScholasticDetail> ClassScholasticDetailModifiedByNavigation { get; set; } = new List<ClassScholasticDetail>();

    // public virtual ICollection<ClassSectionDetail> ClassSectionDetailCreatedByNavigation { get; set; } = new List<ClassSectionDetail>();

    // public virtual ICollection<ClassSectionDetail> ClassSectionDetailModifiedByNavigation { get; set; } = new List<ClassSectionDetail>();

    // public virtual ICollection<ClassSubjectDetail> ClassSubjectDetailCreatedByNavigation { get; set; } = new List<ClassSubjectDetail>();

    // public virtual ICollection<ClassSubjectDetailHistory> ClassSubjectDetailHistoryCreatedByNavigation { get; set; } = new List<ClassSubjectDetailHistory>();

    // public virtual ICollection<ClassSubjectDetailHistory> ClassSubjectDetailHistoryModifiedByNavigation { get; set; } = new List<ClassSubjectDetailHistory>();

    // public virtual ICollection<ClassSubjectDetail> ClassSubjectDetailModifiedByNavigation { get; set; } = new List<ClassSubjectDetail>();

    // public virtual ICollection<CleanerMaster> CleanerMasterCreatedByNavigation { get; set; } = new List<CleanerMaster>();

    // public virtual ICollection<CleanerMaster> CleanerMasterModifiedByNavigation { get; set; } = new List<CleanerMaster>();

    // public virtual CompanyMaster Company { get; set; }

    // public virtual ICollection<CompanyMaster> CompanyMasterCreatedByNavigation { get; set; } = new List<CompanyMaster>();

    // public virtual ICollection<CompanyMaster> CompanyMasterModifiedByNavigation { get; set; } = new List<CompanyMaster>();

    // public virtual ICollection<CountryMaster> CountryMasterCreatedByNavigation { get; set; } = new List<CountryMaster>();

    // public virtual ICollection<CountryMaster> CountryMasterModifiedByNavigation { get; set; } = new List<CountryMaster>();

    // public virtual UserDetails CreatedByNavigation { get; set; }

    // public virtual ICollection<DeptDesigDetails> DeptDesigDetailsCreatedByNavigation { get; set; } = new List<DeptDesigDetails>();

    // public virtual ICollection<DeptDesigDetails> DeptDesigDetailsModifiedByNavigation { get; set; } = new List<DeptDesigDetails>();

    // public virtual ICollection<DeptMaster> DeptMasterCreatedByNavigation { get; set; } = new List<DeptMaster>();

    // public virtual ICollection<DeptMaster> DeptMasterModifiedByNavigation { get; set; } = new List<DeptMaster>();

    // public virtual ICollection<DesigGradeDetails> DesigGradeDetailsCreatedByNavigation { get; set; } = new List<DesigGradeDetails>();

    // public virtual ICollection<DesigGradeDetails> DesigGradeDetailsModifiedByNavigation { get; set; } = new List<DesigGradeDetails>();

    // public virtual ICollection<DesigMaster> DesigMasterCreatedByNavigation { get; set; } = new List<DesigMaster>();

    // public virtual ICollection<DesigMaster> DesigMasterModifiedByNavigation { get; set; } = new List<DesigMaster>();

    // public virtual DesigMaster Designation { get; set; }

    // public virtual ICollection<DesignationGrade> DesignationGradeCreatedByNavigation { get; set; } = new List<DesignationGrade>();

    // public virtual ICollection<DesignationGrade> DesignationGradeModifiedByNavigation { get; set; } = new List<DesignationGrade>();

    // public virtual ICollection<DriverMaster> DriverMasterCreatedByNavigation { get; set; } = new List<DriverMaster>();

    // public virtual ICollection<DriverMaster> DriverMasterModifiedByNavigation { get; set; } = new List<DriverMaster>();

    // public virtual ICollection<EmpAttendanceDetails> EmpAttendanceDetailsCreatedByNavigation { get; set; } = new List<EmpAttendanceDetails>();

    // public virtual ICollection<EmpAttendanceDetailsHistory> EmpAttendanceDetailsHistoryCreatedByNavigation { get; set; } = new List<EmpAttendanceDetailsHistory>();

    // public virtual ICollection<EmpAttendanceDetailsHistory> EmpAttendanceDetailsHistoryModifiedByNavigation { get; set; } = new List<EmpAttendanceDetailsHistory>();

    // public virtual ICollection<EmpAttendanceDetails> EmpAttendanceDetailsModifiedByNavigation { get; set; } = new List<EmpAttendanceDetails>();

    // public virtual ICollection<EmpCatLeaveDetails> EmpCatLeaveDetailsCreatedByNavigation { get; set; } = new List<EmpCatLeaveDetails>();

    // public virtual ICollection<EmpCatLeaveDetailsHistory> EmpCatLeaveDetailsHistoryCreatedByNavigation { get; set; } = new List<EmpCatLeaveDetailsHistory>();

    // public virtual ICollection<EmpCatLeaveDetailsHistory> EmpCatLeaveDetailsHistoryModifiedByNavigation { get; set; } = new List<EmpCatLeaveDetailsHistory>();

    // public virtual ICollection<EmpCatLeaveDetails> EmpCatLeaveDetailsModifiedByNavigation { get; set; } = new List<EmpCatLeaveDetails>();

    // public virtual ICollection<EmpCategoryMaster> EmpCategoryMasterCreatedByNavigation { get; set; } = new List<EmpCategoryMaster>();

    // public virtual ICollection<EmpCategoryMaster> EmpCategoryMasterModifiedByNavigation { get; set; } = new List<EmpCategoryMaster>();

    // public virtual ICollection<EmpDocumentDetails> EmpDocumentDetailsCreatedByNavigation { get; set; } = new List<EmpDocumentDetails>();

    // public virtual ICollection<EmpDocumentDetails> EmpDocumentDetailsModifiedByNavigation { get; set; } = new List<EmpDocumentDetails>();

    // public virtual ICollection<EmpLeaveAvailDetails> EmpLeaveAvailDetailsCreatedByNavigation { get; set; } = new List<EmpLeaveAvailDetails>();

    // public virtual ICollection<EmpLeaveAvailDetails> EmpLeaveAvailDetailsModifiedByNavigation { get; set; } = new List<EmpLeaveAvailDetails>();

    // public virtual ICollection<EmpLeaveDetails> EmpLeaveDetailsCreatedByNavigation { get; set; } = new List<EmpLeaveDetails>();

    // public virtual ICollection<EmpLeaveDetailsHistory> EmpLeaveDetailsHistoryCreatedByNavigation { get; set; } = new List<EmpLeaveDetailsHistory>();

    // public virtual ICollection<EmpLeaveDetailsHistory> EmpLeaveDetailsHistoryModifiedByNavigation { get; set; } = new List<EmpLeaveDetailsHistory>();

    // public virtual ICollection<EmpLeaveDetails> EmpLeaveDetailsModifiedByNavigation { get; set; } = new List<EmpLeaveDetails>();

    // public virtual ICollection<EmpMaster> EmpMasterCreatedByNavigation { get; set; } = new List<EmpMaster>();

    // public virtual ICollection<EmpMaster> EmpMasterModifiedByNavigation { get; set; } = new List<EmpMaster>();

    // public virtual ICollection<EmpProfQualiDetails> EmpProfQualiDetailsCreatedByNavigation { get; set; } = new List<EmpProfQualiDetails>();

    // public virtual ICollection<EmpProfQualiDetails> EmpProfQualiDetailsModifiedByNavigation { get; set; } = new List<EmpProfQualiDetails>();

    // public virtual ICollection<EmpSalaryDetails> EmpSalaryDetailsCreatedByNavigation { get; set; } = new List<EmpSalaryDetails>();

    // public virtual ICollection<EmpSalaryDetailsHistory> EmpSalaryDetailsHistoryCreatedByNavigation { get; set; } = new List<EmpSalaryDetailsHistory>();

    // public virtual ICollection<EmpSalaryDetailsHistory> EmpSalaryDetailsHistoryModifiedByNavigation { get; set; } = new List<EmpSalaryDetailsHistory>();

    // public virtual ICollection<EmpSalaryDetails> EmpSalaryDetailsModifiedByNavigation { get; set; } = new List<EmpSalaryDetails>();

    // public virtual ICollection<EmpSalaryMaster> EmpSalaryMasterCreatedByNavigation { get; set; } = new List<EmpSalaryMaster>();

    // public virtual ICollection<EmpSalaryMasterHistory> EmpSalaryMasterHistoryCreatedByNavigation { get; set; } = new List<EmpSalaryMasterHistory>();

    // public virtual ICollection<EmpSalaryMasterHistory> EmpSalaryMasterHistoryModifiedByNavigation { get; set; } = new List<EmpSalaryMasterHistory>();

    // public virtual ICollection<EmpSalaryMaster> EmpSalaryMasterModifiedByNavigation { get; set; } = new List<EmpSalaryMaster>();

    // public virtual ICollection<EmpSalaryStructureDetails> EmpSalaryStructureDetailsCreatedByNavigation { get; set; } = new List<EmpSalaryStructureDetails>();

    // public virtual ICollection<EmpSalaryStructureDetailsHistory> EmpSalaryStructureDetailsHistoryCreatedByNavigation { get; set; } = new List<EmpSalaryStructureDetailsHistory>();

    // public virtual ICollection<EmpSalaryStructureDetailsHistory> EmpSalaryStructureDetailsHistoryModifiedByNavigation { get; set; } = new List<EmpSalaryStructureDetailsHistory>();

    // public virtual ICollection<EmpSalaryStructureDetails> EmpSalaryStructureDetailsModifiedByNavigation { get; set; } = new List<EmpSalaryStructureDetails>();

    // public virtual ICollection<EmpTypeMaster> EmpTypeMasterCreatedByNavigation { get; set; } = new List<EmpTypeMaster>();

    // public virtual ICollection<EmpTypeMaster> EmpTypeMasterModifiedByNavigation { get; set; } = new List<EmpTypeMaster>();

    // public virtual ICollection<Error> Error { get; set; } = new List<Error>();

    // public virtual ICollection<ExamCategoryMaster> ExamCategoryMasterCreatedByNavigation { get; set; } = new List<ExamCategoryMaster>();

    // public virtual ICollection<ExamCategoryMaster> ExamCategoryMasterModifiedByNavigation { get; set; } = new List<ExamCategoryMaster>();

    // public virtual ICollection<ExamUnitMaster> ExamUnitMasterCreatedByNavigation { get; set; } = new List<ExamUnitMaster>();

    // public virtual ICollection<ExamUnitMaster> ExamUnitMasterModifiedByNavigation { get; set; } = new List<ExamUnitMaster>();

    // public virtual ICollection<ExpenseCategoryMaster> ExpenseCategoryMasterCreatedByNavigation { get; set; } = new List<ExpenseCategoryMaster>();

    // public virtual ICollection<ExpenseCategoryMaster> ExpenseCategoryMasterModifiedByNavigation { get; set; } = new List<ExpenseCategoryMaster>();

    // public virtual ICollection<FeeClassDetails> FeeClassDetailsCreatedByNavigation { get; set; } = new List<FeeClassDetails>();

    // public virtual ICollection<FeeClassDetailsHistory> FeeClassDetailsHistoryCreatedByNavigation { get; set; } = new List<FeeClassDetailsHistory>();

    // public virtual ICollection<FeeClassDetailsHistory> FeeClassDetailsHistoryModifiedByNavigation { get; set; } = new List<FeeClassDetailsHistory>();

    // public virtual ICollection<FeeClassDetails> FeeClassDetailsModifiedByNavigation { get; set; } = new List<FeeClassDetails>();

    // public virtual ICollection<FeesCategoryMaster> FeesCategoryMasterCreatedByNavigation { get; set; } = new List<FeesCategoryMaster>();

    // public virtual ICollection<FeesCategoryMaster> FeesCategoryMasterModifiedByNavigation { get; set; } = new List<FeesCategoryMaster>();

    // public virtual ICollection<FeesDiscountCategoryMaster> FeesDiscountCategoryMasterCreatedByNavigation { get; set; } = new List<FeesDiscountCategoryMaster>();

    // public virtual ICollection<FeesDiscountCategoryMaster> FeesDiscountCategoryMasterModifiedByNavigation { get; set; } = new List<FeesDiscountCategoryMaster>();

    // public virtual ICollection<GenderMaster> GenderMasterCreatedByNavigation { get; set; } = new List<GenderMaster>();

    // public virtual ICollection<GenderMaster> GenderMasterModifiedByNavigation { get; set; } = new List<GenderMaster>();

    // public virtual ICollection<GradeMaster> GradeMasterCreatedByNavigation { get; set; } = new List<GradeMaster>();

    // public virtual ICollection<GradeMaster> GradeMasterModifiedByNavigation { get; set; } = new List<GradeMaster>();

    // public virtual ICollection<HolidayClassDetails> HolidayClassDetailsCreatedByNavigation { get; set; } = new List<HolidayClassDetails>();

    // public virtual ICollection<HolidayClassDetails> HolidayClassDetailsModifiedByNavigation { get; set; } = new List<HolidayClassDetails>();

    // public virtual ICollection<HolidayDeptDetails> HolidayDeptDetailsCreatedByNavigation { get; set; } = new List<HolidayDeptDetails>();

    // public virtual ICollection<HolidayDeptDetails> HolidayDeptDetailsModifiedByNavigation { get; set; } = new List<HolidayDeptDetails>();

    // public virtual ICollection<HolidayMaster> HolidayMasterCreatedByNavigation { get; set; } = new List<HolidayMaster>();

    // public virtual ICollection<HolidayMaster> HolidayMasterModifiedByNavigation { get; set; } = new List<HolidayMaster>();

    // public virtual ICollection<HolidayTypeMaster> HolidayTypeMasterCreatedByNavigation { get; set; } = new List<HolidayTypeMaster>();

    // public virtual ICollection<HolidayTypeMaster> HolidayTypeMasterModifiedByNavigation { get; set; } = new List<HolidayTypeMaster>();

    // public virtual ICollection<InventoryMaster> InventoryMasterCreatedByNavigation { get; set; } = new List<InventoryMaster>();

    // public virtual ICollection<InventoryMaster> InventoryMasterModifiedByNavigation { get; set; } = new List<InventoryMaster>();

    // public virtual ICollection<UserDetails> InverseCreatedByNavigation { get; set; } = new List<UserDetails>();

    // public virtual ICollection<UserDetails> InverseModifiedByNavigation { get; set; } = new List<UserDetails>();

    // public virtual ICollection<ItemLocationMaster> ItemLocationMasterCreatedByNavigation { get; set; } = new List<ItemLocationMaster>();

    // public virtual ICollection<ItemLocationMaster> ItemLocationMasterModifiedByNavigation { get; set; } = new List<ItemLocationMaster>();

    // public virtual ICollection<ItemMaster> ItemMasterCreatedByNavigation { get; set; } = new List<ItemMaster>();

    // public virtual ICollection<ItemMaster> ItemMasterModifiedByNavigation { get; set; } = new List<ItemMaster>();

    // public virtual ICollection<ItemTypeMaster> ItemTypeMasterCreatedByNavigation { get; set; } = new List<ItemTypeMaster>();

    // public virtual ICollection<ItemTypeMaster> ItemTypeMasterModifiedByNavigation { get; set; } = new List<ItemTypeMaster>();

    // public virtual ICollection<LeaveStatusMaster> LeaveStatusMasterCreatedByNavigation { get; set; } = new List<LeaveStatusMaster>();

    // public virtual ICollection<LeaveStatusMaster> LeaveStatusMasterModifiedByNavigation { get; set; } = new List<LeaveStatusMaster>();

    // public virtual ICollection<LeaveTypeMaster> LeaveTypeMasterCreatedByNavigation { get; set; } = new List<LeaveTypeMaster>();

    // public virtual ICollection<LeaveTypeMaster> LeaveTypeMasterModifiedByNavigation { get; set; } = new List<LeaveTypeMaster>();

    // public virtual ICollection<LocationMaster> LocationMasterCreatedByNavigation { get; set; } = new List<LocationMaster>();

    // public virtual ICollection<LocationMaster> LocationMasterModifiedByNavigation { get; set; } = new List<LocationMaster>();

    // public virtual ICollection<MaritalStatus> MaritalStatusCreatedByNavigation { get; set; } = new List<MaritalStatus>();

    // public virtual ICollection<MaritalStatus> MaritalStatusModifiedByNavigation { get; set; } = new List<MaritalStatus>();

    // public virtual ICollection<MarksGradeMaster> MarksGradeMasterCreatedByNavigation { get; set; } = new List<MarksGradeMaster>();

    // public virtual ICollection<MarksGradeMaster> MarksGradeMasterModifiedByNavigation { get; set; } = new List<MarksGradeMaster>();

    // public virtual UserDetails ModifiedByNavigation { get; set; }

    // public virtual ICollection<NotificationReceiverMaster> NotificationReceiverMasterCreatedByNavigation { get; set; } = new List<NotificationReceiverMaster>();

    // public virtual ICollection<NotificationReceiverMaster> NotificationReceiverMasterModifiedByNavigation { get; set; } = new List<NotificationReceiverMaster>();

    // public virtual ICollection<ParentMaster> ParentMasterCreatedByNavigation { get; set; } = new List<ParentMaster>();

    // public virtual ICollection<ParentMaster> ParentMasterModifiedByNavigation { get; set; } = new List<ParentMaster>();

    // public virtual ICollection<PaymentModeMaster> PaymentModeMasterCreatedByNavigation { get; set; } = new List<PaymentModeMaster>();

    // public virtual ICollection<PaymentModeMaster> PaymentModeMasterModifiedByNavigation { get; set; } = new List<PaymentModeMaster>();

    // public virtual ICollection<PaymentTypeMode> PaymentTypeModeCreatedByNavigation { get; set; } = new List<PaymentTypeMode>();

    // public virtual ICollection<PaymentTypeMode> PaymentTypeModeModifiedByNavigation { get; set; } = new List<PaymentTypeMode>();

    // public virtual ICollection<Privileges> PrivilegesCreatedByNavigation { get; set; } = new List<Privileges>();

    // public virtual ICollection<Privileges> PrivilegesModifiedByNavigation { get; set; } = new List<Privileges>();

    // public virtual ICollection<ProfessionMaster> ProfessionMasterCreatedByNavigation { get; set; } = new List<ProfessionMaster>();

    // public virtual ICollection<ProfessionMaster> ProfessionMasterModifiedByNavigation { get; set; } = new List<ProfessionMaster>();

    // public virtual ICollection<PublisherMaster> PublisherMasterCreatedByNavigation { get; set; } = new List<PublisherMaster>();

    // public virtual ICollection<PublisherMaster> PublisherMasterModifiedByNavigation { get; set; } = new List<PublisherMaster>();

    // public virtual ICollection<QualificationMaster> QualificationMasterCreatedByNavigation { get; set; } = new List<QualificationMaster>();

    // public virtual ICollection<QualificationMaster> QualificationMasterModifiedByNavigation { get; set; } = new List<QualificationMaster>();

    // public virtual ICollection<RegistrationMaster> RegistrationMasterCreatedByNavigation { get; set; } = new List<RegistrationMaster>();

    // public virtual ICollection<RegistrationMaster> RegistrationMasterModifiedByNavigation { get; set; } = new List<RegistrationMaster>();

    // public virtual ICollection<RelationTypeMaster> RelationTypeMasterCreatedByNavigation { get; set; } = new List<RelationTypeMaster>();

    // public virtual ICollection<RelationTypeMaster> RelationTypeMasterModifiedByNavigation { get; set; } = new List<RelationTypeMaster>();

    // public virtual ICollection<ReligionMaster> ReligionMasterCreatedByNavigation { get; set; } = new List<ReligionMaster>();

    // public virtual ICollection<ReligionMaster> ReligionMasterModifiedByNavigation { get; set; } = new List<ReligionMaster>();

    // public virtual ICollection<RoleMaster> RoleMasterCreatedByNavigation { get; set; } = new List<RoleMaster>();

    // public virtual ICollection<RoleMaster> RoleMasterModifiedByNavigation { get; set; } = new List<RoleMaster>();

    // public virtual ICollection<RolePrivileges> RolePrivilegesCreatedByNavigation { get; set; } = new List<RolePrivileges>();

    // public virtual ICollection<RolePrivileges> RolePrivilegesModifiedByNavigation { get; set; } = new List<RolePrivileges>();

    // public virtual ICollection<RouteDetails> RouteDetailsCreatedByNavigation { get; set; } = new List<RouteDetails>();

    // public virtual ICollection<RouteDetails> RouteDetailsModifiedByNavigation { get; set; } = new List<RouteDetails>();

    // public virtual ICollection<RouteLocationMaster> RouteLocationMasterCreatedByNavigation { get; set; } = new List<RouteLocationMaster>();

    // public virtual ICollection<RouteLocationMaster> RouteLocationMasterModifiedByNavigation { get; set; } = new List<RouteLocationMaster>();

    // public virtual ICollection<RouteMaster> RouteMasterCreatedByNavigation { get; set; } = new List<RouteMaster>();

    // public virtual ICollection<RouteMaster> RouteMasterModifiedByNavigation { get; set; } = new List<RouteMaster>();

    // public virtual ICollection<RouteStopDetails> RouteStopDetailsCreatedByNavigation { get; set; } = new List<RouteStopDetails>();

    // public virtual ICollection<RouteStopDetails> RouteStopDetailsModifiedByNavigation { get; set; } = new List<RouteStopDetails>();

    // public virtual ICollection<SMSTask> SMSTaskCreatedByNavigation { get; set; } = new List<SMSTask>();

    // public virtual ICollection<SMSTaskHistory> SMSTaskHistoryCreatedByNavigation { get; set; } = new List<SMSTaskHistory>();

    // public virtual ICollection<SMSTaskHistory> SMSTaskHistoryModifiedByNavigation { get; set; } = new List<SMSTaskHistory>();

    // public virtual ICollection<SMSTask> SMSTaskModifiedByNavigation { get; set; } = new List<SMSTask>();

    // public virtual ICollection<SMSTaskSchedule> SMSTaskScheduleCreatedByNavigation { get; set; } = new List<SMSTaskSchedule>();

    // public virtual ICollection<SMSTaskSchedule> SMSTaskScheduleModifiedByNavigation { get; set; } = new List<SMSTaskSchedule>();

    // public virtual ICollection<SMSTaskSmtpDetails> SMSTaskSmtpDetailsCreatedByNavigation { get; set; } = new List<SMSTaskSmtpDetails>();

    // public virtual ICollection<SMSTaskSmtpDetails> SMSTaskSmtpDetailsModifiedByNavigation { get; set; } = new List<SMSTaskSmtpDetails>();

    // public virtual ICollection<SMSTaskStatusMaster> SMSTaskStatusMasterCreatedByNavigation { get; set; } = new List<SMSTaskStatusMaster>();

    // public virtual ICollection<SMSTaskStatusMaster> SMSTaskStatusMasterModifiedByNavigation { get; set; } = new List<SMSTaskStatusMaster>();

    // public virtual ICollection<SalaryCode> SalaryCodeCreatedByNavigation { get; set; } = new List<SalaryCode>();

    // public virtual ICollection<SalaryCode> SalaryCodeModifiedByNavigation { get; set; } = new List<SalaryCode>();

    // public virtual ICollection<SalaryDesigGradeDetails> SalaryDesigGradeDetailsCreatedByNavigation { get; set; } = new List<SalaryDesigGradeDetails>();

    // public virtual ICollection<SalaryDesigGradeDetailsHistory> SalaryDesigGradeDetailsHistoryCreatedByNavigation { get; set; } = new List<SalaryDesigGradeDetailsHistory>();

    // public virtual ICollection<SalaryDesigGradeDetailsHistory> SalaryDesigGradeDetailsHistoryModifiedByNavigation { get; set; } = new List<SalaryDesigGradeDetailsHistory>();

    // public virtual ICollection<SalaryDesigGradeDetails> SalaryDesigGradeDetailsModifiedByNavigation { get; set; } = new List<SalaryDesigGradeDetails>();

    // public virtual ICollection<SalaryHeadMaster> SalaryHeadMasterCreatedByNavigation { get; set; } = new List<SalaryHeadMaster>();

    // public virtual ICollection<SalaryHeadMaster> SalaryHeadMasterModifiedByNavigation { get; set; } = new List<SalaryHeadMaster>();

    // public virtual ICollection<SalaryType> SalaryTypeCreatedByNavigation { get; set; } = new List<SalaryType>();

    // public virtual ICollection<SalaryTypeMaster> SalaryTypeMasterCreatedByNavigation { get; set; } = new List<SalaryTypeMaster>();

    // public virtual ICollection<SalaryTypeMaster> SalaryTypeMasterModifiedByNavigation { get; set; } = new List<SalaryTypeMaster>();

    // public virtual ICollection<SalaryType> SalaryTypeModifiedByNavigation { get; set; } = new List<SalaryType>();

    // public virtual ICollection<ScholasticMaster> ScholasticMasterCreatedByNavigation { get; set; } = new List<ScholasticMaster>();

    // public virtual ICollection<ScholasticMaster> ScholasticMasterModifiedByNavigation { get; set; } = new List<ScholasticMaster>();

    // public virtual ICollection<ScholasticUnitDetail> ScholasticUnitDetailCreatedByNavigation { get; set; } = new List<ScholasticUnitDetail>();

    // public virtual ICollection<ScholasticUnitDetail> ScholasticUnitDetailModifiedByNavigation { get; set; } = new List<ScholasticUnitDetail>();

    // public virtual SchoolMaster School { get; set; }

    // public virtual ICollection<SchoolContactMaster> SchoolContactMasterCreatedByNavigation { get; set; } = new List<SchoolContactMaster>();

    // public virtual ICollection<SchoolContactMaster> SchoolContactMasterModifiedByNavigation { get; set; } = new List<SchoolContactMaster>();

    // public virtual ICollection<SchoolMaster> SchoolMasterCreatedByNavigation { get; set; } = new List<SchoolMaster>();

    // public virtual ICollection<SchoolMaster> SchoolMasterModifiedByNavigation { get; set; } = new List<SchoolMaster>();

    // public virtual ICollection<SectionMaster> SectionMasterCreatedByNavigation { get; set; } = new List<SectionMaster>();

    // public virtual ICollection<SectionMaster> SectionMasterModifiedByNavigation { get; set; } = new List<SectionMaster>();

    // public virtual ICollection<SessionMaster> SessionMasterCreatedByNavigation { get; set; } = new List<SessionMaster>();

    // public virtual ICollection<SessionMaster> SessionMasterModifiedByNavigation { get; set; } = new List<SessionMaster>();

    // public virtual ICollection<SmtpDetails> SmtpDetailsCreatedByNavigation { get; set; } = new List<SmtpDetails>();

    // public virtual ICollection<SmtpDetails> SmtpDetailsModifiedByNavigation { get; set; } = new List<SmtpDetails>();

    // public virtual ICollection<StateMaster> StateMasterCreatedByNavigation { get; set; } = new List<StateMaster>();

    // public virtual ICollection<StateMaster> StateMasterModifiedByNavigation { get; set; } = new List<StateMaster>();

    // public virtual ICollection<StudentAchievements> StudentAchievementsCreatedByNavigation { get; set; } = new List<StudentAchievements>();

    // public virtual ICollection<StudentAchievements> StudentAchievementsModifiedByNavigation { get; set; } = new List<StudentAchievements>();

    // public virtual ICollection<StudentAttendanceDetails> StudentAttendanceDetailsCreatedByNavigation { get; set; } = new List<StudentAttendanceDetails>();

    // public virtual ICollection<StudentAttendanceDetails> StudentAttendanceDetailsModifiedByNavigation { get; set; } = new List<StudentAttendanceDetails>();

    // public virtual ICollection<StudentCommentDetails> StudentCommentDetailsCreatedByNavigation { get; set; } = new List<StudentCommentDetails>();

    // public virtual ICollection<StudentCommentDetailsHistory> StudentCommentDetailsHistoryCreatedByNavigation { get; set; } = new List<StudentCommentDetailsHistory>();

    // public virtual ICollection<StudentCommentDetailsHistory> StudentCommentDetailsHistoryModifiedByNavigation { get; set; } = new List<StudentCommentDetailsHistory>();

    // public virtual ICollection<StudentCommentDetails> StudentCommentDetailsModifiedByNavigation { get; set; } = new List<StudentCommentDetails>();

    // public virtual ICollection<StudentFeeDetails> StudentFeeDetailsCreatedByNavigation { get; set; } = new List<StudentFeeDetails>();

    // public virtual ICollection<StudentFeeDetailsHistory> StudentFeeDetailsHistoryCreatedByNavigation { get; set; } = new List<StudentFeeDetailsHistory>();

    // public virtual ICollection<StudentFeeDetailsHistory> StudentFeeDetailsHistoryModifiedByNavigation { get; set; } = new List<StudentFeeDetailsHistory>();

    // public virtual ICollection<StudentFeeDetails> StudentFeeDetailsModifiedByNavigation { get; set; } = new List<StudentFeeDetails>();

    // public virtual ICollection<StudentGradeDetails> StudentGradeDetailsCreatedByNavigation { get; set; } = new List<StudentGradeDetails>();

    // public virtual ICollection<StudentGradeDetailsHistory> StudentGradeDetailsHistoryCreatedByNavigation { get; set; } = new List<StudentGradeDetailsHistory>();

    // public virtual ICollection<StudentGradeDetailsHistory> StudentGradeDetailsHistoryModifiedByNavigation { get; set; } = new List<StudentGradeDetailsHistory>();

    // public virtual ICollection<StudentGradeDetails> StudentGradeDetailsModifiedByNavigation { get; set; } = new List<StudentGradeDetails>();

    // public virtual ICollection<StudentMarksDetails> StudentMarksDetailsCreatedByNavigation { get; set; } = new List<StudentMarksDetails>();

    // public virtual ICollection<StudentMarksDetailsHistory> StudentMarksDetailsHistoryCreatedByNavigation { get; set; } = new List<StudentMarksDetailsHistory>();

    // public virtual ICollection<StudentMarksDetailsHistory> StudentMarksDetailsHistoryModifiedByNavigation { get; set; } = new List<StudentMarksDetailsHistory>();

    // public virtual ICollection<StudentMarksDetails> StudentMarksDetailsModifiedByNavigation { get; set; } = new List<StudentMarksDetails>();

    // public virtual ICollection<StudentMaster> StudentMasterCreatedByNavigation { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistoryCreatedByNavigation { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<StudentMasterHistory> StudentMasterHistoryModifiedByNavigation { get; set; } = new List<StudentMasterHistory>();

    // public virtual ICollection<StudentMaster> StudentMasterModifiedByNavigation { get; set; } = new List<StudentMaster>();

    // public virtual ICollection<StudentReportCardDetails> StudentReportCardDetailsCreatedByNavigation { get; set; } = new List<StudentReportCardDetails>();

    // public virtual ICollection<StudentReportCardDetailsHistory> StudentReportCardDetailsHistoryCreatedByNavigation { get; set; } = new List<StudentReportCardDetailsHistory>();

    // public virtual ICollection<StudentReportCardDetailsHistory> StudentReportCardDetailsHistoryModifiedByNavigation { get; set; } = new List<StudentReportCardDetailsHistory>();

    // public virtual ICollection<StudentReportCardDetails> StudentReportCardDetailsModifiedByNavigation { get; set; } = new List<StudentReportCardDetails>();

    // public virtual ICollection<StudentReportCardMaster> StudentReportCardMasterCreatedByNavigation { get; set; } = new List<StudentReportCardMaster>();

    // public virtual ICollection<StudentReportCardMasterHistory> StudentReportCardMasterHistoryCreatedByNavigation { get; set; } = new List<StudentReportCardMasterHistory>();

    // public virtual ICollection<StudentReportCardMasterHistory> StudentReportCardMasterHistoryModifiedByNavigation { get; set; } = new List<StudentReportCardMasterHistory>();

    // public virtual ICollection<StudentReportCardMaster> StudentReportCardMasterModifiedByNavigation { get; set; } = new List<StudentReportCardMaster>();

    // public virtual ICollection<SubjectCategoryDetails> SubjectCategoryDetailsCreatedByNavigation { get; set; } = new List<SubjectCategoryDetails>();

    // public virtual ICollection<SubjectCategoryDetailsHistory> SubjectCategoryDetailsHistoryCreatedByNavigation { get; set; } = new List<SubjectCategoryDetailsHistory>();

    // public virtual ICollection<SubjectCategoryDetailsHistory> SubjectCategoryDetailsHistoryModifiedByNavigation { get; set; } = new List<SubjectCategoryDetailsHistory>();

    // public virtual ICollection<SubjectCategoryDetails> SubjectCategoryDetailsModifiedByNavigation { get; set; } = new List<SubjectCategoryDetails>();

    // public virtual ICollection<SubjectMaster> SubjectMasterCreatedByNavigation { get; set; } = new List<SubjectMaster>();

    // public virtual ICollection<SubjectMaster> SubjectMasterModifiedByNavigation { get; set; } = new List<SubjectMaster>();

    // public virtual ICollection<SupplierMaster> SupplierMasterCreatedByNavigation { get; set; } = new List<SupplierMaster>();

    // public virtual ICollection<SupplierMaster> SupplierMasterModifiedByNavigation { get; set; } = new List<SupplierMaster>();

    // public virtual ICollection<SystemParameters> SystemParametersCreatedByNavigation { get; set; } = new List<SystemParameters>();

    // public virtual ICollection<SystemParameters> SystemParametersModifiedByNavigation { get; set; } = new List<SystemParameters>();

    // public virtual ICollection<TeacherClassDetails> TeacherClassDetailsCreatedByNavigation { get; set; } = new List<TeacherClassDetails>();

    // public virtual ICollection<TeacherClassDetails> TeacherClassDetailsModifiedByNavigation { get; set; } = new List<TeacherClassDetails>();

    // public virtual ICollection<TeacherDocumentDetails> TeacherDocumentDetailsCreatedByNavigation { get; set; } = new List<TeacherDocumentDetails>();

    // public virtual ICollection<TeacherDocumentDetails> TeacherDocumentDetailsModifiedByNavigation { get; set; } = new List<TeacherDocumentDetails>();

    // public virtual ICollection<TeacherMaster> TeacherMasterCreatedByNavigation { get; set; } = new List<TeacherMaster>();

    // public virtual ICollection<TeacherMaster> TeacherMasterModifiedByNavigation { get; set; } = new List<TeacherMaster>();

    // public virtual ICollection<TeacherQualificationDetails> TeacherQualificationDetailsCreatedByNavigation { get; set; } = new List<TeacherQualificationDetails>();

    // public virtual ICollection<TeacherQualificationDetails> TeacherQualificationDetailsModifiedByNavigation { get; set; } = new List<TeacherQualificationDetails>();

    // public virtual ICollection<TeacherSectionDetails> TeacherSectionDetailsCreatedByNavigation { get; set; } = new List<TeacherSectionDetails>();

    // public virtual ICollection<TeacherSectionDetails> TeacherSectionDetailsModifiedByNavigation { get; set; } = new List<TeacherSectionDetails>();

    // public virtual ICollection<TeacherSubjectDetails> TeacherSubjectDetailsCreatedByNavigation { get; set; } = new List<TeacherSubjectDetails>();

    // public virtual ICollection<TeacherSubjectDetails> TeacherSubjectDetailsModifiedByNavigation { get; set; } = new List<TeacherSubjectDetails>();

    // public virtual ICollection<TimeTableClassPeriodDetails> TimeTableClassPeriodDetailsCreatedByNavigation { get; set; } = new List<TimeTableClassPeriodDetails>();

    // public virtual ICollection<TimeTableClassPeriodDetailsHistory> TimeTableClassPeriodDetailsHistoryCreatedByNavigation { get; set; } = new List<TimeTableClassPeriodDetailsHistory>();

    // public virtual ICollection<TimeTableClassPeriodDetailsHistory> TimeTableClassPeriodDetailsHistoryModifiedByNavigation { get; set; } = new List<TimeTableClassPeriodDetailsHistory>();

    // public virtual ICollection<TimeTableClassPeriodDetails> TimeTableClassPeriodDetailsModifiedByNavigation { get; set; } = new List<TimeTableClassPeriodDetails>();

    // public virtual ICollection<TimeTableDetailsHistory> TimeTableDetailsHistoryCreatedByNavigation { get; set; } = new List<TimeTableDetailsHistory>();

    // public virtual ICollection<TimeTableDetailsHistory> TimeTableDetailsHistoryModifiedByNavigation { get; set; } = new List<TimeTableDetailsHistory>();

    // public virtual ICollection<TimeTablePeriodMaster> TimeTablePeriodMasterCreatedByNavigation { get; set; } = new List<TimeTablePeriodMaster>();

    // public virtual ICollection<TimeTablePeriodMaster> TimeTablePeriodMasterModifiedByNavigation { get; set; } = new List<TimeTablePeriodMaster>();

    // public virtual ICollection<TimeTableSessions> TimeTableSessionsCreatedByNavigation { get; set; } = new List<TimeTableSessions>();

    // public virtual ICollection<TimeTableSessions> TimeTableSessionsModifiedByNavigation { get; set; } = new List<TimeTableSessions>();

    // public virtual ICollection<TimeTableSetupDetails> TimeTableSetupDetailsCreatedByNavigation { get; set; } = new List<TimeTableSetupDetails>();

    // public virtual ICollection<TimeTableSetupDetailsHistory> TimeTableSetupDetailsHistoryCreatedByNavigation { get; set; } = new List<TimeTableSetupDetailsHistory>();

    // public virtual ICollection<TimeTableSetupDetailsHistory> TimeTableSetupDetailsHistoryModifiedByNavigation { get; set; } = new List<TimeTableSetupDetailsHistory>();

    // public virtual ICollection<TimeTableSetupDetails> TimeTableSetupDetailsModifiedByNavigation { get; set; } = new List<TimeTableSetupDetails>();

    // public virtual ICollection<TimeTableSubstitutionDetails> TimeTableSubstitutionDetailsCreatedByNavigation { get; set; } = new List<TimeTableSubstitutionDetails>();

    // public virtual ICollection<TimeTableSubstitutionDetailsHistory> TimeTableSubstitutionDetailsHistoryCreatedByNavigation { get; set; } = new List<TimeTableSubstitutionDetailsHistory>();

    // public virtual ICollection<TimeTableSubstitutionDetailsHistory> TimeTableSubstitutionDetailsHistoryModifiedByNavigation { get; set; } = new List<TimeTableSubstitutionDetailsHistory>();

    // public virtual ICollection<TimeTableSubstitutionDetails> TimeTableSubstitutionDetailsModifiedByNavigation { get; set; } = new List<TimeTableSubstitutionDetails>();

    // public virtual RoleMaster UserRole { get; set; }

    // public virtual ICollection<VehicleExpenseDetails> VehicleExpenseDetailsCreatedByNavigation { get; set; } = new List<VehicleExpenseDetails>();

    // public virtual ICollection<VehicleExpenseDetails> VehicleExpenseDetailsModifiedByNavigation { get; set; } = new List<VehicleExpenseDetails>();

    // public virtual ICollection<VehicleMaster> VehicleMasterCreatedByNavigation { get; set; } = new List<VehicleMaster>();

    // public virtual ICollection<VehicleMaster> VehicleMasterModifiedByNavigation { get; set; } = new List<VehicleMaster>();

    // public virtual ICollection<VehicleTypeMaster> VehicleTypeMasterCreatedByNavigation { get; set; } = new List<VehicleTypeMaster>();

    // public virtual ICollection<VehicleTypeMaster> VehicleTypeMasterModifiedByNavigation { get; set; } = new List<VehicleTypeMaster>();

    // public virtual ICollection<VendorMaster> VendorMasterCreatedByNavigation { get; set; } = new List<VendorMaster>();

    // public virtual ICollection<VendorMaster> VendorMasterModifiedByNavigation { get; set; } = new List<VendorMaster>();

    // public virtual ICollection<VisitorMaster> VisitorMasterCreatedByNavigation { get; set; } = new List<VisitorMaster>();

    // public virtual ICollection<VisitorMaster> VisitorMasterModifiedByNavigation { get; set; } = new List<VisitorMaster>();

    // public virtual ICollection<VoucherMaster> VoucherMasterCreatedByNavigation { get; set; } = new List<VoucherMaster>();

    // public virtual ICollection<VoucherMaster> VoucherMasterModifiedByNavigation { get; set; } = new List<VoucherMaster>();
}