// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolPortal.Entities.Models;

public partial class DriverMaster
{
    public Guid Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public string FathersName { get; set; }

    public string MothersName { get; set; }

    public Guid QualificationId { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public Guid CityId { get; set; }

    public Guid StateId { get; set; }

    public Guid CountryId { get; set; }

    public string ZipCode { get; set; }

    public string MobileNumber { get; set; }

    public string PhoneNumber { get; set; }

    public string DriverImage { get; set; }

    public string LicenceNumber { get; set; }

    public DateTime? LicenceIssueDate { get; set; }

    public DateTime? LicenceValidUptoDate { get; set; }

    public string LicenceDescription { get; set; }

    public string LicenceImage { get; set; }

    public string LicenceType { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }
}