// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolPortal.Entities.Models;

public partial class ParentMaster
{
    public Guid Id { get; set; }

    public Guid StudentGUID { get; set; }

    public string ParentFirstName { get; set; }

    public string ParentLastName { get; set; }

    public DateTime? ParentDOB { get; set; }

    public Guid QualificationId { get; set; }

    public string Occupation { get; set; }

    public decimal? AnnualIncome { get; set; }

    public Guid DesignationId { get; set; }

    public string Phone { get; set; }

    public string Mobile { get; set; }

    public string Email { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public Guid CityId { get; set; }

    public Guid StateId { get; set; }

    public Guid CountryId { get; set; }

    public string ZipCode { get; set; }

    public string OfficeAddress1 { get; set; }

    public string OfficeAddress2 { get; set; }

    public Guid OfficeCityId { get; set; }

    public Guid OfficeStateId { get; set; }

    public Guid OfficeCountryId { get; set; }

    public string OfficeZipCode { get; set; }

    public string OfficePhone { get; set; }

    public string Image { get; set; }

    public Guid RelationTypeId { get; set; }

    public Guid SchoolId { get; set; }

    public Guid CompanyId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }
}