// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolPortal.Entities.Models;

public partial class SMSTaskSmtpDetails
{
    public Guid Id { get; set; }

    public string FromAddress { get; set; }

    public string GatewayName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Subject { get; set; }

    public string BodyText { get; set; }

    public Guid TaskId { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public string MessageSubject { get; set; }

    public string MessageBody { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }
}