// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolPortal.Entities.Models;

public partial class StudentReportCardDetailsHistory
{
    public Guid Id { get; set; }

    public Guid ReportCardId { get; set; }

    public Guid SubjectId { get; set; }

    public decimal? QuarterMarks { get; set; }

    public decimal? FA1Marks { get; set; }

    public decimal? FA2Marks { get; set; }

    public decimal? SAMarks { get; set; }

    public string Grade { get; set; }

    public string FA1Grade { get; set; }

    public string FA2Grade { get; set; }

    public string SAGrade { get; set; }

    public decimal? TotalMarks { get; set; }

    public string TotalGrade { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public decimal? TotalMarksQuarter { get; set; }

    public decimal? TotalMarksFA1 { get; set; }

    public decimal? TotalMarksFA2 { get; set; }

    public decimal? TotalMarksSA { get; set; }

    public decimal? TotalMarks_Final { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }
}