// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolPortal.Entities.Models;

public partial class TimeTableSetupDetails
{
    public Guid Id { get; set; }

    public TimeSpan SchoolStartTime { get; set; }

    public TimeSpan SchoolEndTime { get; set; }

    public TimeSpan PeriodStartTime { get; set; }

    public int TotalPeriods { get; set; }

    public int PeriodDuration { get; set; }

    public int RecessDuration { get; set; }

    public int RecessAfterPeriod { get; set; }

    public int? FruitRecessDuration { get; set; }

    public int? FruitRecessAfterPeriod { get; set; }

    public Guid SessionId { get; set; }

    public Guid CompanyId { get; set; }

    public Guid SchoolId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Status { get; set; }

    public string StatusMessage { get; set; }
}